### ISSUE TITLE
FireSALE Not Working

### ISSUE THREAD

**Issue by james182** [firesale/firesale#1]
there seems to an issue with the "firesale" and "FireSALE" in navigating to sections. 

Cannot redeclare class Module_Firesale in /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/addons/default/modules/firesale/details.php on line 476

**Comment by jHoldroyd** [comment]
I've just been checking over what is and isn't there from our back-ups and everything (apart from one image) is in tact and as it should be. Could you please make sure the module folder is lowercase and not installed in both default and shared_addons please? There seems to be some sort of conflict.

**Comment by james182** [comment]
I change the folders name to lowercase and it's only in default folder, but same thing.. 

with this link:
http://localhost/PyroCMS-Professional-v2.1.2/admin/firesale/products

i get this:
Fatal error: Cannot redeclare class Module_Firesale in /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/addons/default/modules/firesale/details.php on line 476

**Comment by james182** [comment]
seems to be this in details.php:

public function info()
    {
        return $this->firesale->info($this->information(), $this->language_file);
    }

**Comment by jHoldroyd** [comment]
I've assigned Chris to look into it, hopefully we can get to the bottom of it for you.

**Comment by MarceauKa** [comment]
I've got the same problem...

I've just reinstall PyroCMS with the module folder to lowercase and it works great. But i've still got a problem when PyroCMS is in french...

**Comment by jHoldroyd** [comment]
We've just tested the issue and Chris has already got a fix ready which we'll push in a few hours along with a number of other small tweaks
