### ISSUE TITLE
Product image not displaying in cart

### ISSUE THREAD

**Issue by jellis** [firesale/firesale#100]
Using FF15 on OSX.

Added product to cart.
Went to cart.
Image shown said "Awaiting images"

Product has multiple images associated with it, confirmed in admin area and viewing product directly.

Using vanilla installation of PyroCMS 2.1.4 Community and vanilla Firesale (current as at time of posting)

No custom themes installed.

**Comment by jHoldroyd** [comment]
That should be taken care of now, just a small issue with the logic used in our default views.
