### ISSUE TITLE
Problem in the Order page in admin

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#107]
I have just tried to order a product in the frontend and I set "**Italy**" as Country and choosed "**My Billing and Shipping addresses are the same.**".
In the CP in the order list in the "**Shipping Details**" the country is set correctly but in the "**Billing Detail**" is set to "**United Kingdom**" instead "**Italy**"

**Comment by jHoldroyd** [comment]
Another JS issue, when you checked the radio it would only update selects. This is now fixed and will also show the form after checked so you can easily verify the address if you wish.
