### ISSUE TITLE
Shipping methods in frontend

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#108]
I have added a shipping company in my CP but it doesn't shows up in the shipping methods in the checkout page

**Comment by jHoldroyd** [comment]
Can I just ask what settings did you apply to the band you created (min and max weight/price) as well as the products values for size and weight. If it falls outside the allotted boundaries it won't show up as a viable method of shipping, if you don't think this is the case let me know and I'll attempt to replicate the situation you're experiencing.

**Comment by jHoldroyd** [comment]
Moved this to 1.1.0 due to a lack of information and needing to get 1.0.4 released to fix a number of critical bugs

**Comment by ChristianGiupponi** [comment]
Sorry @jHoldroyd tomorrow I will look at it and I will give you more info!

**Comment by jHoldroyd** [comment]
It's not a problem, just wanted to let you know it'd been moved to the next version.

**Comment by jHoldroyd** [comment]
Closing this issue now, done a lot more retesting of the shipping module and have taken care of the bands. I'll be pushing it soon once it's cleaned up a little more.
