### ISSUE TITLE
Routes enhancement

### ISSUE THREAD

**Issue by MarceauKa** [firesale/firesale#110]
Hi !

Is it possible to have translation items for routes?
I think it's impossible because of CodeIgniter's engine... Someone may have an idea?

**Comment by jHoldroyd** [comment]
It's something we've considered and may have an idea or two on how to implement it in a future version.

There's a few ways we can achieve it and may be penciled in for 1.2 as far as I'm aware right now. It'll become slightly less important for certain pages like products that will be changed to /category-slug/product-slug rather than the current product/product-slug route it has now but there are still quite a few pages that will benefit from it if we can pull it off.

**Comment by MarceauKa** [comment]
Yeah, thx for responding so quickly!

Ps: I just saw that your night coding with lot of loud music has bore fruit :p (My english is not too weird?)
Congrats for FireSale-Documentation.

**Comment by jHoldroyd** [comment]
About the different methods though, the one I think we'll go with is a smaller version of the routes module that's on the Pyro store. Which will let you change/modify your routes how you want them from the admin and it'll write the file for you - automatically installing the current routes for your language. I don't think it'll be terribly difficult and when we do enable that, we'll also install all the routes required on install making it that much easier to get up and running - as well as enabling extra modules to install their routes too.

Thank you, the hacked together platform for them is done (and works quite well, even responsive)...it's just time to do that annoying part of filling in all those blank white pages.

**Comment by jHoldroyd** [comment]
At the moment it's looking like the basic routes system (possibly advanced) will be in for v1.1.0 to make installation easier and allow you to control your route options from the control panel. What we're hoping to do from there is add functions to get the recommended redirect URL for front-end pages as well as allow for dynamic information like category slug, product slug, product id, etc.

**Comment by jHoldroyd** [comment]
Just as an update this system is almost complete, still some testing and admin integration to do, but the core system is done and working.

**Comment by jHoldroyd** [comment]
This is now done and fully working in the 1.1 branch which should be released in the next few days!
