### ISSUE TITLE
Product - and if it is a costume?

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#119]
Let's assume that in my store I sell only costumes...how can I handle the size? (small, large etc..)
I don't think that is a good idea insert the same product with a different name...and if the backoffice has a optional field in which I can insert comma separated, the size of the costume?

What do you think?

Same speach for a different colors...

**Comment by chrisnharvey** [comment]
Hi Christian, we have an attributes module in development that should cater your needs.

**Comment by jHoldroyd** [comment]
You should have access to it, I gave you access to all of the in-development modules on the organisation yesterday

**Comment by ChristianGiupponi** [comment]
Oops, sorry!
I haven't seen all the modules yet!
