### ISSUE TITLE
cart and order warning

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#121]
When I add a product to the cart:

A PHP Error was encountered

Severity: Warning

Message: Parameter 1 to Events_Firesale_attributes::page_build() expected to be a reference, value given

Filename: libraries/Events.php

Line Number: 147

Same warning in users/orders/

I think is because of the address2 value that in my case is empty!

**Comment by jHoldroyd** [comment]
You might want to read where the error was coming from and think about which module would have been better to post this on :p

It was all down to the events system needing a tiny fix and everything should be working again. You'll need to pull down new copies of SEO and Attributes to have it fixed as this was not a core issue - as the warning will tell you!
