### ISSUE TITLE
Failed install and uninstall

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#125]
Firesale 1.0.4 
PyroCMS Version 2.1.3 Community
### Steps:
- Copied Firesale folder to addons/shared-addons/modules/
- Clicked Install button in Add-ons interface
- Received Error 500
- Returned to Add-ons Interface
- Clicked Uninstall button
- Received Error 500
- Returned to Add-ons Interface
- Clicked Delete button
- Received Error 500
### Logs:

[Sun Sep 30 14:37:21 2012] [error] [client 99.107.254.245] PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/emcycling.com/system/cms/modules/streams_core/models/streams_m.php on line 449, referer: http://emcycling.com/admin/modules

[Sun Sep 30 14:37:40 2012] [error] [client 99.107.254.245] PHP Fatal error:  Call to a member function result_array() on a non-object in /var/www/emcycling.com/addons/shared_addons/modules/firesale/plugin.php on line 207, referer: http://emcycling.com/admin/modules

[Sun Sep 30 14:37:46 2012] [error] [client 99.107.254.245] PHP Fatal error:  Call to a member function result_array() on a non-object in /var/www/emcycling.com/addons/shared_addons/modules/firesale/models/products_m.php on line 261, referer: http://emcycling.com/admin/modules

**Comment by joshuarlowry** [comment]
Determined reason we can't uninstall is probably due to failed install.  firesale_products table wasn't created.

**Comment by joshuarlowry** [comment]
Was able to perform uninstall.

Added code to products_m.php in delete_all_products()

If what was returned from the get is empty, then do nothing because there is nothing to do.

**Comment by joshuarlowry** [comment]
I looked into the first error:

Cannot use object of type stdClass as array in /var/www/emcycling.com/system/cms/modules/streams_core/models/streams_m.php on line 449

It appears that streams_core does not save the stream to cache correctly if you are storing 'by slug' as it appears Firesale does.

I did a var_dump on $this->streams_cache and all the streams we have are stored by 'id'.  I was able to see the firesale_categories stream, but there were 2 identical ones.  One of them was stored by 'id' and the other by 'slug' or 'namespace' (firesale_categories).  I think this should have rather been 1 stream with it stored as an associative array ['firesale']['id'].

**Comment by jHoldroyd** [comment]
Firstly let me say thank you for the effort to try and debug the issue yourself and not just leaving it to us.

However this is the same issue I found a few weeks ago after 2.1.3 was released. We actually submitted a pull request to Pyro to fix this and is included in 2.1.4 onwards, which, if you read the requirements section in the readme, is why we require Pyro version 2.1.4 and above.
