### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#126]
Firesale 1.0.4
Pyrocms 2.1.4

When I try to install I get the following error message:

An Error Was Encountered
invalid_fieldtype [add_field] 

Uninstall works fine

Database created two new tables
    firesale_categories
    firesale_products

Not sure where to go.

**Comment by joshuarlowry** [comment]
Performed a full reinstall on my dev server and tried to install.

Got a cleaner error on the page that just said: "Could not install the module" in a red box.

When trying to go to the module using the control panel I get the following error:

A Database Error Occurred
Error Number: 1146

Table 'emcycling.default_firesale_orders_items' doesn't exist

SELECT SUM(`qty`) AS `count`, SUM(`qty` \* `price`) AS `sales`, date_format(`created`, "%Y-%m") AS `month` FROM `default_firesale_orders_items` GROUP BY `month` ORDER BY `month` ASC LIMIT 12

Filename: /var/www/emcycling.sagfdne.com/addons/shared_addons/modules/firesale/plugin.php

Line Number: 207

Uninstall still works.

**Comment by jHoldroyd** [comment]
You need to install the Multiple field type, as per the installation guidelines in the readme, which I've posted below:

## Installation
1. Clone yourself a copy of the FireSale core
2. Move everything to either your PyroCMS shared_addons or addons/default folder
3. If you are using PyroCMS Community you need to install also the [Multiple Relationship](https://github.com/parse19/PyroStreams-Multiple-Relationships) field type
4. Install the core via the admin modules panel
5. Install the other two modules by the same method
6. Go into settings and choose your preferred options, we strongly advise you to select yes for routes
7. Below you'll find a number of routes we suggest you install; a number of features will not work without them
