### ISSUE TITLE
Items fail to appear in cart

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#131]
Firesale: 1.0.4
Pyrocms: 2.1.4 Community

I did finally get everything installed.  Now that I am testing things out I realize I can't add things to my cart.  I don't get any errors on screen or in my httpd logs.  I'm not sure what to do.

**Comment by joshuarlowry** [comment]
Yeah, I had an ' in the title of the product.  That is why it didn't work.  It might be a good idea to validate this at product creation/edit time.

**Comment by ChristianGiupponi** [comment]
I can confirm the same issue

**Comment by chrisnharvey** [comment]
I will look into this one today and get back to you with a fix.

Sent from my iPhone

On 11 Oct 2012, at 08:22 AM, Christian Giupponi notifications@github.com
wrote:

I can confirm the same issue

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/issues/131#issuecomment-9330880.

**Comment by jHoldroyd** [comment]
This should be taken care of now, products with any title should now be acceptable.

**Comment by ChristianGiupponi** [comment]
Where did you push it? Master or develop? I have just update my repo but it doesn't work

**Comment by jHoldroyd** [comment]
Sorry I think that's just in 1.1/develop I'll get it into the master branch now too, sorry about that

**Comment by ChristianGiupponi** [comment]
Great! It works now :)
