### ISSUE TITLE
1.1 Create new product

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#148]
When you create a new product and then you press the "Save" button you will be redirect to the frontend homepage instead the products list

EDIT:

same problem when you edit a product

**Comment by jHoldroyd** [comment]
1.1 Technically requires PyroCMS 2.1.5 that hasn't been released yet, hence why we haven't launched. That's the cause of your issues at the moment

**Comment by ChristianGiupponi** [comment]
ah sorry, I didn't know that!

**Comment by jHoldroyd** [comment]
No worries, we haven't put it up anywhere yet and that's the main reason we haven't launched 1.1 yet.

**Comment by ChristianGiupponi** [comment]
With 2.1.5 do you mean the current 2.1/Develop? Where can I download it to test the module?

**Comment by jHoldroyd** [comment]
Yeah the current development version should be ok to use, we're testing on it. It's just a couple changes in the streams_core so you can use 2.1.4 with that and it'll work, we use it on our site and at work - fixes a number of bugs and contains a few key changes to streams to allow us to fully validate streams properly

**Comment by ChristianGiupponi** [comment]
I have downloaded it but it doesn't seems to work, same errors...well I will wait untill the 2.1.5 to test FireSale!

**Comment by jHoldroyd** [comment]
Same errors on install or product creation?

**Comment by ChristianGiupponi** [comment]
On the products list, it doesn't add the product id to the urls

**Comment by jHoldroyd** [comment]
If you could check routes, what's in your product route?

**Comment by jHoldroyd** [comment]
Just seen what the default routes are and I need to sort those out, but if you edit the product route and delete {{ any }} and replace it with the product slug or id it'll update everything and should be fine.
