### ISSUE TITLE
Errors loading categories & products

### ISSUE THREAD

**Issue by wturrell** [firesale/firesale#15]
Firstly this all looks awesome, looking forward to following progress as you move towards a release.  Well done.

I created a sample product and a category but then I did something (amongst other things I temporarily disabled then re-enabled the shipping module to see if I could supply a product without weight/dimensions) and now:

My product page (which was working) now just shows 'Coming Soon'.    

Browsing to category urls (e.g. /categories/uncategorised, /categories/toys) returns this error:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND `default_firesale_products`.`status` = '1') ORDER BY `default_firesal' at line 4
SELECT `default_firesale_products`.* FROM `default_firesale_products` WHERE (`default_firesale_products`.`category` IN () AND `default_firesale_products`.`status` = '1') ORDER BY `default_firesale_products`.`title` ASC LIMIT 15
```

Everything looks like it's there on the admin pages and in default_firesale_categories and default_firesale_products.

I'm using the 2.1 branch of PyroCMS community, btw.

Thanks,
William

**Comment by jHoldroyd** [comment]
That looks like an issue with one of the latest changes I pushed for gathering parent categories. I'll look into it now and with that push shipping weights, etc. aren't required anymore - it just classes them at 0 since a lot of people don't know/want to add that extra info.

**Comment by jHoldroyd** [comment]
I'll leave the issue open until you can confirm if it's fixed or not. Can't test it myself at the moment

**Comment by wturrell** [comment]
Thanks. The admin Shipping Options change worked fine, but the categories still seem broken.

It'll load when the category has children (e.g. /toys/animals), but not when it doesn't (e.g. /postcards).  I feel like I ought to be to work out where it's breaking but I've failed to so far.

Also, I realise the views aren't done yet now (sorry, hadn't read that bit properly) but the link to the zip file in README.md is broken - could you fix that?

**Comment by jHoldroyd** [comment]
Sorry about that, site is migrating at the moment. I've updated the readme with the new link and I've added it below (just in my dropbox).

I'm just working on a fix for shipping at the moment, but as soon as I've got that taken care of I'll look into this issue a little more. 

Theme: https://dl.dropbox.com/u/32596384/fs-theme.zip

**Comment by jHoldroyd** [comment]
Just done another "fix" for this issue and yet it's still performing the same query regardless of what I send to it as the where parameter. Still trying to figure it out but it's a weird one, it's definitely the get_entries call in front_category/index that's doing it but no matter what I send as where it still messes up

**Comment by jHoldroyd** [comment]
I take that back, there was an almost identical query in the model to get the total number of products, updated that too and everything should be working as intended again.

**Comment by jHoldroyd** [comment]
I should also mention that while I was changing things I made it multilevel compatible - whereas before it would check if it was a top-level category (ie. parent of 0), it now checks if it has children in general

**Comment by wturrell** [comment]
Thanks, all working now.
