### ISSUE TITLE
Adding a 'Firesale' navigation item directs the page to a non-existant route

### ISSUE THREAD

**Issue by weejames** [firesale/firesale#150]
Hi,

Using the PyroCMS admin I added a navigation item to the 'Firesale' module.

This added a url to the navigation of http://mysite.com/firesale

That route isn't set up on installation, nor is it listed on your installlation docs.

I'd add a pull request but I'm not sure how you'd want to handle that.  Personally I'd have it redirect to the '/products' route.

**Comment by weejames** [comment]
Should have said I'm using the develop/1.1 branch - i need the features it has and the site shouldnt be going live til after its finalised.

**Comment by jHoldroyd** [comment]
I think that menu item is a little misleading and we'll get rid of it soon; having said that we're working on getting products and categories into the navigation section to just link to.

As you're running 1.1 though you can simply point a uri link to /category and that will list all of your products in one place, you can also change the slug for this in the routes section to whatever you want.

Navigation is a bit of an issue at the moment and we're trying to figure out the best compromise for the solution we can, it's a part of PyroCMS that we can't really tap into and it's causing headaches all over the place. But the above should do the trick and we'll hopefully have a better solution soon.
