### ISSUE TITLE
It should be possible to modify for longer cur_format

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#151]
Error Number: 1406

Data too long for column 'cur_format' at row 1

UPDATE `default_firesale_currency` SET `cur_code` = 'LT', `title` = 'Default', `slug` = 'default', `enabled` = '1', `cur_tax` = '21', `cur_format` = '{{ price }} Lt', `cur_format_dec` = ',', `cur_format_sep` = '.', `cur_format_num` = '1', `cur_mod` = '+|', `exch_rate` = '1', `updated` = '2012-10-28 12:49:08' WHERE `id` = '1'

/modules/streams_core/models/row_m.php

Line Number: 1080

**Comment by jHoldroyd** [comment]
The currency format allows for 32 characters which should be more than enough but I'm guessing it's being inserted as HTML entities which would explain the issue you're experiencing. If you check the source code of the page with that error you'll see each curly bracket will be &# 123; or &# 125; which means the string you're inputting is around 34 chars.

**Comment by hsq** [comment]
In some cases the field length is not changed while updating the module in pyro. Check your field length in your table. That might be your solution...

**Comment by jHoldroyd** [comment]
I've had to increase the allowed character limit for that field as it's the streams_core or active record that is encoding the entities and not something we have control over. To stop yourself having to update or reinstall FireSale just run this query on your database:

```
ALTER TABLE `default_firesale_currency` CHANGE `cur_format` `cur_format` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL 
```
