### ISSUE TITLE
Consistently getting error on install

### ISSUE THREAD

**Issue by adrienne** [firesale/firesale#153]
(I've searched the closed issues and mine is not covered.)

Details
- PyroCMS version: 2.1.4 Community
- Multiple Relationships fieldtype is enabled
- FireSale 1.0.4 **OR** 1.1.0

Using either the version of Firesale from GitHub OR the version available at the PyroCMS Addons page, I get the following error on install:

```
An Error Was Encountered
invalid_stream [get_stream]
```

No streams or database tables are created.

Please help! This is seriously causing me an issue, I have to get this site up and running ASAP!

**Comment by adrienne** [comment]
Also: I tried purchasing and installing PyroStreams, to see if that would fix the error, and it does NOT. Installed or uninstalled, I still get the same error.

**Comment by jHoldroyd** [comment]
Chris has just pushed a fix to what we think is causing this. Make sure you can fully uninstall before trying again with the newest version to avoid any conflicts.

**Comment by adrienne** [comment]
That seems to have gotten it! I will report back if I run into more issues!
