### ISSUE TITLE
Translate gateway descriptions

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#155]
There are a few new gateways that require translations. See d436c94731

**Comment by chrisnharvey** [comment]
Added a couple of extra gateways. See 97a85f7f79

**Comment by ChristianGiupponi** [comment]
Done for italian lang: 7d7bc9f310d5e0b0bd481f944ffc088da96a782c

**Comment by chrisnharvey** [comment]
Thanks Christian, appreciate it.

**Comment by jHoldroyd** [comment]
I'd say we've got all that we can get done with this prior to 1.1 and if anyone wants to take care of the missing items, feel free! Closing now.
