### ISSUE TITLE
Documentation page error

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#159]
When browsers language is defined not EN 
    http://www.getfiresale.org/documentation gives - 404.

A PHP Error was encountered
Severity: Warning
Message: file_get_contents(/var/www/vhosts/getfiresale.org/httpdocs/addons/shared_addons/modules/documentation/docs/lt/_data): failed to open stream: No such file or directory
Filename: controllers/front.php
Line Number: 25

**Comment by jHoldroyd** [comment]
I'll get that sorted as soon as I can, thanks for reporting it. It should default to English if the selected file isn't found, but it seems it's not doing it
