### ISSUE TITLE
Category slug in sort url

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#165]
Maybe it is simple, but i can't get trough:
How ordering of only one category products should be done?

```
{{ ordering }}
    <li><a href="{{ firesale:url route='category-custom' }}order/{{ key }}">{{ title }}</a></li>
{{ /ordering }}
```

Gives all sorted products in the shop.

**Comment by jHoldroyd** [comment]
The core currently doesn't support user customised sorting by only one category, it's a global thing to keep navigation consistent. I don't think it would be that difficult to do to change the cookie to be per-category but it's not something we're looking to add as core functionality as we feel it's good how it is.

**Comment by from2day** [comment]
Fair answer
