### ISSUE TITLE
Routes errors

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#169]
There is a problem in the routes tabs: http://www.diigo.com/item/image/32ya3/5x8c

**Comment by ChristianGiupponi** [comment]
Never mind, now it works...

**Comment by jHoldroyd** [comment]
I'm guessing it required a reinstall? I just added that last night and it's not in the upgrade path just yet.

**Comment by ChristianGiupponi** [comment]
Yes I have reinstalled the module! 

-- Inviato dal mio Galaxy Nexus

Jamie Holdroyd notifications@github.com ha scritto:
