### ISSUE TITLE
Product page in admin - do not consider taxes?

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#173]
I have tried to create a new product.
First of all I have edited the default currency to set taxes at 21% but when I go to the create product page and I insert the first value and then I press the tab button it doesnt show me the price with the taxes.

http://awesomescreenshot.com/07elka8e8

It report 0.00 is it correct?

**Comment by chrisnharvey** [comment]
This is currently being updated, I'm hoping to have all this finished today.

**Comment by ChristianGiupponi** [comment]
ah ok, so I will not send the other issue I found untill you finish :)

**Comment by jHoldroyd** [comment]
Yeah we're currently adding the multiple taxes feature and once Chris has his part done I'll be going through and updating the JavaScript features in the admin to correctly take it into account and this should be working again.

Just out of interest though, what is the other issue?

**Comment by ChristianGiupponi** [comment]
The other issue was in the frontend in the cart.
In the products list I saw the prices with the taxes included but once I added one of them in the cart, the product(s) appeared without taxed and the set it to 0.00 but with the last update of Chris it seems to be solved.

Unfortunatly I'm not able to wait untill someone finished their work on a module before post issue :P

**Comment by ChristianGiupponi** [comment]
But I will check it better just when Chris finished!

**Comment by jHoldroyd** [comment]
Closing this now as it should be fixed.
