### ISSUE TITLE
tax calculation not correct in admin

### ISSUE THREAD

**Issue by hsq** [firesale/firesale#178]
When using the automatic tax calculation in the admin, it goes wrong. Probably somewhere hard coded that it should be 20%.
I changed it here to 21% and the cart gave me wrong results.

Please check for any tax calculations to make it use the tax settings.

url:    /admin/firesale/products/edit/1

**Comment by jHoldroyd** [comment]
I'll see what we can do to look into this but I don't know if there's much point since 1.1 will be tagged today and the entire tax system will be updated and replaced with something far better.

**Comment by hsq** [comment]
Ahhh... great... I cannot wait... ;-)
