### ISSUE TITLE
Installation [Question]

### ISSUE THREAD

**Issue by boethius** [firesale/firesale#179]
Hi

I've used CodeIgniter for a while and I am familiar with routes, but the installation instructions for FireSale are very confusing. I've managed to install FireSale but I am stuck at trying to get products and categories to display.

Do I set up the routes manually in the routes.php, in that case, which one, the one for PyroCMS or the one in the modules? Or do I set up pages with tags, in that case which?

A few examples would have made this experience so much less frustrating and clearer, maybe even a screenshot or two, and a list of files that need the modifications as well.

Thank you for your reply.

**Comment by jHoldroyd** [comment]
Apologies for your frustration and as a note the routes file you need to edit is the one found in system/cms/config/routes.php

We'd presumed that most people knew which routes file we meant as if it was the modules routes file we would have done it already. Coming with 1.1 the module requires write access to the correct routes file and will add all of them for you as well as allowing you to configure them from the administration panel to define the URLs you'd like to use.

The routes direct the site to the correct controller and they are not pages, you can simply point to a category or product, for example out of the box /category/uncategorised should work.

Our documentation is coming together and can be found [here](https://www.getfiresale.org/documentation) and while it is still lacking we are working on it daily to bring it up to par with where it needs to be. FireSale is still very very new and we're trying to find the right balance between improvements, documentation and support as well as all of the other things we have going on; however 1.1 should mark a vast improvement over the current main branch and we should be tagging that today.

Again I apologise for the issues you've had and if you need any more help just let me know here or via support@getfiresale.org

**Comment by boethius** [comment]
No apologies needed, but thank you very much for your quick and informative reply. If it is all the same to you, I would like to continue this discussion on GitHub so that this information is available to others until the documentation is complete.

I might be misunderstanding a fundamental aspect of CI, but how do I route to an add-on, specifically, what should the correct routes be?

Currently it is routing to a Page Not Found, and I'm not sure about the controller path.

``` php
$route['services(/:any)']               = 'firesale/front_category$1';
```

Thanks again!

**Comment by jHoldroyd** [comment]
I'm presuming you're running 1.0.5 from the master branch? If so I'd recommend upgrading to 1.1 and from there you can edit the routes via the administration panel, having said that you could force the category into index to avoid it trying to go to the wrong function like so:

```
$route['services(/:any)'] = 'firesale/front_category/index$1';
```

That way it's guaranteed to go to the correct path as there's only the one function available in the controller that the route is targeting; the others are handled by another route.

**Comment by boethius** [comment]
Hi Please mark this as solved. Pulling 1.1 solved the issue. Thanks!
