### ISSUE TITLE
Numerous price inconsistencies

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#183]
Throughout the buying process and especially after switching currency prices seem to change and become somewhat "random" and can change from page to page.

**Comment by chrisnharvey** [comment]
Got some fixes almost redy to push, been doing some extensive testing.

**Comment by jHoldroyd** [comment]
Nice, I took care of the items issue and the reason it was working locally earlier was because you'd created the rows whereas it didn't do that in details yet. Not a massive issue and it's in there now but it's something to note for any sites already running with taxes in 1.1-dev.

Also, Skype!

**Comment by jHoldroyd** [comment]
Not sure which one this comes under, but when changing currency with items in the cart the rounding option isn't being applied.
