### ISSUE TITLE
Remove delete button for default currency

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#186]
The default currency can not be deleted. Perhaps we could remove the delete button for the default currency.

**Comment by joshuarlowry** [comment]
How do I change the default currency?  It is giving me an error when I try to modify it.  Our site only handles USD, so having GBP on the site at all will be very confusing.

**Comment by jHoldroyd** [comment]
What's the error that it's giving you? You should be able to modify it and that way you still keep the default currency and don't need to create a second.
