### ISSUE TITLE
Can't understand difference between Taxes and Currency

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#189]
Hi,
FireSale has two different tabs for currency and Taxes but I can't understand why in the currency one the is the taxe percent while in the taxes tab the is a fild text with a number.
What is this for?
I need to set it to the same value on the taxes percent? Can't just use the percent rate?

**Comment by jHoldroyd** [comment]
The tax rate set in a currency is the default applied to that currency for the available tax rates. Variable tax rates are there to be chosen on a per-product basis as many countries have different rates of tax for different products - eg. food, technology, fuel, etc. all have different rates. But these rates may be different in varying countries so you can set them based on the currency too.
