### ISSUE TITLE
Duplicate error messages on checkout

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#191]
Duplicate error messages are displayed when there are errors on the billing details (even "requires shipping" is set to "no")

**Comment by chrisnharvey** [comment]
I've assigned @jHoldroyd as this is a part that he wrote.

**Comment by jHoldroyd** [comment]
Moved to flashdata as opposed to form validation, makes it easier to manage, removes the requirement for PHP at the top of the file...oh and actually works too which is a nice little bonus.
