### ISSUE TITLE
Settings not created on upgrade

### ISSUE THREAD

**Issue by swilla** [firesale/firesale#192]
Upgrade from 1.\* to 1.1 did not create new settings:

firesale_currency
firesale_perpage
firesale_login
image_square

**Comment by chrisnharvey** [comment]
I'll look into this one for you. Thanks for letting us know about this
issue.

Sent from my iPhone

On 16 Nov 2012, at 05:21 PM, Steve Williamson notifications@github.com
wrote:

Upgrade from 1.\* to 1.1 did not create new settings:

firesale_currency
firesale_perpage
firesale_login
image_square

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/issues/192.

**Comment by jHoldroyd** [comment]
I haven't had a chance to check but I'm pretty sure those are pre 1.1 settings and should have been added with the 1.\* branch you're using.
