### ISSUE TITLE
If slug starts with integer type logic returns ID

### ISSUE THREAD

**Issue by swilla** [firesale/firesale#193]
If Slug is: '10-pack-lessons'. 

This returns

```
$type = ( 0 + $id_slug > 0 ? 'id' : 'slug' );
```

ID instead of SLUG

**Comment by swilla** [comment]
For some reason PHP takes the leading number from the string and adds it. I suggest switching to is_numeric() as I've tested this with a bunch of different number string combos and it seems to work consistently.

**Comment by chrisnharvey** [comment]
You're right, not too sure why it was not done this way in the first place.
Thanks for pointing this one out. We'll get on it.

Sent from my iPhone

On 16 Nov 2012, at 06:38 PM, Steve Williamson notifications@github.com
wrote:

For some reason PHP takes the leading number from the string and adds it. I
suggest switching to is_numeric as I've tested this with a bunch of
different number string combos and it seems to work consistently.

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/issues/193#issuecomment-10457061.

**Comment by jHoldroyd** [comment]
It was originally done like that because is_numeric occasionally gave the exact opposite problem as you're having, it was reading certain slugs as numeric when they weren't. I'll check it over and try to find a better solution.

**Comment by swilla** [comment]
Maybe this will work:

```
$type = is_numeric($id_slug) && is_int(($id_slug + 0)) ? 'id' : 'slug';
```

My tests all passed.

**Comment by jHoldroyd** [comment]
Thanks I'll get that in now, run a few tests and hopefully get this one closed :)

**Comment by jHoldroyd** [comment]
That's in for both products and categories since they had the same issue. Thanks for reporting and the suggested fix!
