### ISSUE TITLE
Missing product fields in admin backend

### ISSUE THREAD

**Issue by nickrichwi** [firesale/firesale#195]
I seem to have a lot of missing field inputs for products on the admin backend. 

I am in the US and ive gone thru every setting and file and it always shows a GBP symbol on the form page.

And the product categories box, I can't click or select any of the categories listed.

**Comment by jHoldroyd** [comment]
Which version of FireSale are you using? and just as a note the admin will only use your first (default) currency to avoid any conflicts, price changes etc. so if USD isn't currency 1 you may want to change it and see how you get on. As for the other issues we'll look into them for you.

**Comment by nickrichwi** [comment]
I just upgraded to 1.1.0 from 1.0.4. I had to manually change the default to USD. 
I might have figured out the issue with the fields missing, im getting some missing files from the streams core- field_asset - multiple that I need to figure out why, files are there but the url is slightly incorrect.

**Comment by nickrichwi** [comment]
I have fixed the missing fields  .. due to a bad server config for css and js files not being output thru php. 

Only have the price problem now.

**Comment by jHoldroyd** [comment]
We're still looking into replicating this issue and not had any luck so far. We'll keep digging though and see what we can find

**Comment by nickrichwi** [comment]
http://a22095a3c9b523613f13-25ed30938afcc520c684fe7fb365e4f1.r53.cf1.rackcdn.com/1353619576.2012-11-223.22_.34pm_.png
[Missing price currently how it looks](http://a22095a3c9b523613f13-25ed30938afcc520c684fe7fb365e4f1.r53.cf1.rackcdn.com/1353619576.2012-11-223.22_.34pm_.png)

http://a22095a3c9b523613f13-25ed30938afcc520c684fe7fb365e4f1.r53.cf1.rackcdn.com/1353619576.2012-11-189.06_.56pm_.png
[javascript was broke and showed pounds before fix](http://a22095a3c9b523613f13-25ed30938afcc520c684fe7fb365e4f1.r53.cf1.rackcdn.com/1353619576.2012-11-189.06_.56pm_.png)

**Comment by nickrichwi** [comment]
Ok made a little progress there was a setting in the Settings -> General -> Currency was set to &pound;. I did not expect the setting to be in general .. figured it would have been in FireSale. My product fields now have no currency marks at all ( see previous post ). Poking around it seems that there are not any...

**Comment by jHoldroyd** [comment]
Going to open this one again so we can remember to change it, it should have been done already and I thought it had been...not sure what happened to it
