### ISSUE TITLE
In backend product page no category title

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#196]
I've fresh firesale install. But after some time of usage categories titles disappears from category Drag&Drop window in product edit page, only ids are shown.

Tried to reinstall, problem appears again. In other places: product list, frontend everything works fine.

**Comment by jHoldroyd** [comment]
We've experienced this once before somewhere else, we'll take a look and see what we can do to fix it for you

**Comment by from2day** [comment]
What is the meaning of function "category_fix". When categories are shown as numbers, this fix, deletes all category associations to products

**Comment by jHoldroyd** [comment]
There's an issue with the multiple field-type that would save and re-save categories multiple times, the fix removes them before saving so you aren't left with repeat entries in the database

**Comment by jHoldroyd** [comment]
Just as a test, can you run the following query on your database and see if it fixes it:

```
UPDATE `default_data_streams` SET `title_column` = 'title' WHERE `stream_slug` = 'firesale_categories';
```

Want to make sure that the title column is set correctly, otherwise it may just be using the ID. If that fixes it I'm not sure what caused it, but it is the most likely fix for the problem.

**Comment by from2day** [comment]
Yes, that fixes the issue. 
I have been doing few firesale module reinstalls in a row, but cannot test this now.

**Comment by jHoldroyd** [comment]
So somewhere the categories title hadn't been set, not sure what's caused it but we'll keep an eye out for the issue and take care of it as and when we can. Thanks for letting us know though
