### ISSUE TITLE
Pagination links works not correctly

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#197]
When using tag {{ pagination.links }} it generates page links:

```
category-title/15
category-title/30
...
```

that becomes:

```
http://my-domain.com/category/category-title/category-title/15
...
```

with category title twice, that does not work.
Where pagination can be configured, or is this a bug ? :)

**Comment by jHoldroyd** [comment]
I'll look into the now, it's most likely an issue with routes that we missed, thanks for letting us know

**Comment by jHoldroyd** [comment]
Should be sorted now
