### ISSUE TITLE
Price formatting issue

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#199]
There is a problem with the prices formatting to 3 decimal places in some instances. This is resolved when using {{ price_formatted }} but is quite annoying.

**Comment by jHoldroyd** [comment]
Just doing this one quickly since I'm already in the file

**Comment by chrisnharvey** [comment]
There are still a few places where this problem occurs, reopening.

**Comment by jHoldroyd** [comment]
Any examples? It should have been sorted at the root of the issue, when it's pulled out of products...strange

**Comment by jHoldroyd** [comment]
This should finally be resolved with the last updates I pushed to take care of a few issues with the JS vs PHP pricing.

**Comment by chrisnharvey** [comment]
Reopening. There are still a few places where this occurs.

**Comment by chrisnharvey** [comment]
I think this one is now fixed with my latest commits to the 1.2/develop branch... Finally!

**Comment by jHoldroyd** [comment]
"Your commits", who came up with the bloody fix?!
