### ISSUE TITLE
Assets Error

### ISSUE THREAD

**Issue by james182** [firesale/firesale#2]
in link changed firesale to FireSALE to get it to work.

Using this link: http://localhost/PyroCMS-Professional-v2.1.2/admin/FireSALE/gateways

But then you get this error:

Fatal error: Uncaught exception 'Asset_Exception' with message 'Found no files matching system/cms/modules/pages/css/dashboard.css' in /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/libraries/Asset.php:1129 Stack trace: #0 /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/libraries/Asset.php(1249): Asset::find_files('module::dashboa...', 'css') #1 /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/libraries/Asset.php(1013): Asset::files_to_render('css', 'extra') #2 /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/libraries/Asset.php(886): Asset::render_css('extra', NULL, Array) #3 /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/libraries/Template.php(227): Asset::render('extra') #4 /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/modules/pages/controllers/pages.php(240): Template->build('pages/page', NULL, false, false) #5 /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/modules/pages/controllers/pages.php(72): in /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/system/cms/libraries/Asset.php on line 1129

**Comment by jHoldroyd** [comment]
Yeah we had a pretty bad data loss just before the initial commit and while we recovered most things it would seem we didn't recover everything. Luckily we have other backups which I'll be getting a hold of very soon and this issue should be resolved.

**Comment by james182** [comment]
ok thanks mate.
