### ISSUE TITLE
Adding Product Error

### ISSUE THREAD

**Issue by james182** [firesale/firesale#20]
Can't add product

A Database Error Occurred

Error Number: 1048

Column 'row_id' cannot be null

INSERT INTO `default_firesale_products_firesale_categories` (`row_id`, `firesale_products_id`, `firesale_categories_id`) VALUES (NULL, '18', '2')

Filename: /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/addons/default/modules/firesale/models/products_m.php

Line Number: 240

**Comment by jHoldroyd** [comment]
Taken care of, sorry about that.
