### ISSUE TITLE
Downloadable Products

### ISSUE THREAD

**Issue by mcryan** [firesale/firesale#204]
Hi,

Is there any support for downloadable products with an unlimited amount of stock? If not, are there any plans for such features?

**Comment by chrisnharvey** [comment]
I have been working on a digital downloads module for FireSale. I can give
you access to the private repo if you like.

Sent from my iPhone

On 23 Nov 2012, at 01:45 PM, Marco Ryan notifications@github.com wrote:

Hi,

Is there any support for downloadable products with an unlimited amount of
stock? If not, are there any plans for such features?

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/issues/204.

**Comment by mcryan** [comment]
That would be great. I'd be happy to contribute to it if you need some help?

**Comment by chrisnharvey** [comment]
That would be great! I've given you access to the FireSale-Digital repo and a few others if you want to test those? Any feedback you can give would be very helpful.

Enjoy!

**Comment by jHoldroyd** [comment]
Closing this now
