### ISSUE TITLE
Category status gets set to "Draft" on edit

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#205]
When editing a category, the status does not update to show the status of the category that is being edited. It always shows "Draft".

**Comment by jHoldroyd** [comment]
Quick question, was SEO installed at the same time? If so it's more than likely a lingering JS issue, if not something new and interesting is up

**Comment by chrisnharvey** [comment]
If I'm honest, I don't think it was.

Sent from my iPhone

On 23 Nov 2012, at 09:52 PM, Jamie Holdroyd notifications@github.com
wrote:

Quick question, was SEO installed at the same time? If so it's more than
likely a lingering JS issue, if not something new and interesting is up

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/issues/205#issuecomment-10670512.

**Comment by jHoldroyd** [comment]
Somewhere the array was being passed instead of a simple value that it wasn't checking for, fixed now though
