### ISSUE TITLE
Is it possible to overload admin view?

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#206]
I've tried to overload orders view in admin. The path seems not working:
    shared_addons/themes/my-theme/views/admin/modules/firesale/admin/orders/index.php

**Comment by chrisnharvey** [comment]
As the admin panel has a different theme, you will need to do your
overloading in your admin theme. Usually /system/cms/themes/pyrocms

Sent from my iPhone

On 25 Nov 2012, at 03:36 PM, paulius notifications@github.com wrote:

I've tried to overload orders view in admin. The path seems not working:
shared_addons/themes/my-theme/views/admin/modules/firesale/admin/orders/index.php

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/issues/206.

**Comment by from2day** [comment]
Of course. Thanks.
