### ISSUE TITLE
Quick product edit shows price input error

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#209]
When quick edit product, price input is red. Validation does not allow currency symbols, but is added automatically. 
I use currency of two symbols.

**Comment by jHoldroyd** [comment]
Can you give an example of the currency you use?

**Comment by jHoldroyd** [comment]
Ok nevermind, I think I already know the answer and a fix is on the way

**Comment by jHoldroyd** [comment]
There we go, tested on a range of currencies at the start and end of the string, including "Lt" since that's what I think you're using as you've reported an issue before and included that.

**Comment by from2day** [comment]
Works correctly, great!
