### ISSUE TITLE
link path issue

### ISSUE THREAD

**Issue by james182** [firesale/firesale#21]
My i suggest that in order to prevent linking issues you replace the '/' with {{ url:site }} instead.

Example:

Replace
     /category/{{ slug }}
With
    {{ url:site }}category/{{ slug }}

**Comment by jHoldroyd** [comment]
Thanks for the suggestion, I've put it in for version 1.0.0

**Comment by jHoldroyd** [comment]
This should have been closed along with the default views that were added in the last few days, closing now.
