### ISSUE TITLE
Small PayPal issue

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#210]
When PayPal express returns to FireSale, it does not mark the order as paid or complete the order in any way.

I have a fix for this and will push later.

**Comment by joshuarlowry** [comment]
Has this been pushed yet?

**Comment by jHoldroyd** [comment]
Not yet, last I heard it was proving to be a little more difficult than expected. You should see it up and 1.1.1 tagged tomorrow, with 1.1.2 following quickly with product modifiers/variants later in the week.

**Comment by jcastillotx** [comment]
Chris any status on the push. Thanks

**Comment by chrisnharvey** [comment]
Sorting this one out now. Will push in a few minutes, just doing some final testing.

**Comment by chrisnharvey** [comment]
I see why I delayed this one. Working with the PayPal Sandbox is painful.

**Comment by jcastillotx** [comment]
Ok still getting no charges when I use Paypal express. It takes me to paypal and I see the order but when I pay nothing goes through.

**Comment by jHoldroyd** [comment]
I think Chris has a fix for this that just needs pushed, I'll see if he can get that done tonight for you.

**Comment by jcastillotx** [comment]
Thanks and let me know what happens
