### ISSUE TITLE
Issues with setting pricing for products

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#211]
When setting pricing in the admin panel, sometimes the javascript comes back with a different number to what the PHP does with obscure numbers. It's usually a penny out so not a huge problem.

**Comment by jHoldroyd** [comment]
I'll look into it, I know there's a few issues to look into with quick editing too.

**Comment by jHoldroyd** [comment]
JavaScript seems to use a slightly different rounding method to PHP. JS rounds the last number up by one whereas PHP just cuts it off at the point you asked it to and this is where the issue stemmed from, for example:

```
Original Number: 131.07 (without tax)
PHP: 157.28
JavaScript: 157.29
```

I changed the default method of rounding in our price formatting function and it seems to have taken care of the problem.
