### ISSUE TITLE
Cleanup formatting and currencies

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#213]
There are a lot of inconsistencies with "price", "price_tax" etc.

I think "price" should be the value before tax and "price_tax" should be the value after tax.

Also, currencies needs a bit of a cleanup, as does taxes. I've assigned myself to the taxes cleanup issue.

**Comment by jHoldroyd** [comment]
I'm not going to touch the variable names until we do the rebuild for 1.3.0 but I will take care of the rest

**Comment by jHoldroyd** [comment]
Moving this to 1.3.0 as it makes far more sense to do it with the rebuild than now. We've fixed most (if not all) of the inconsistencies with currencies so I think we're good for now.
