### ISSUE TITLE
Cleanup formatting and taxes

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#214]
There are a lot of inconsistencies with "price", "price_tax" etc.

I think "price" should be the value before tax and "price_tax" should be the value after tax.

Also, taxes needs a bit of a cleanup, as does currencies. I've assigned @jHoldroyd to the currencies cleanup issue.

**Comment by jHoldroyd** [comment]
Those changes will be made in a future version. Closing this one as done now, any further changes can be made in a minor update or in the rebuild for 1.3
