### ISSUE TITLE
PayPal IPN

### ISSUE THREAD

**Issue by ghost** [firesale/firesale#218]
How does FireSale work with PayPal IPN?

Do I need to setup a route and view?

**Comment by jHoldroyd** [comment]
IPN was deprecated from the CI-Merchant library and during development for 1.1 we updated to the latest version which no longer supports it. There's a number of reasons for the move, but the biggest driver for this is the fact that PayPal have made the IPN redundant. The API version of their gateways is free, more reliable and much easier to work with.

If you really want to use it you'll need to get a copy of the old IPN library for CI merchant and update it to work with the new system, as well as create a view for FireSale to use it.

**Comment by joshuarlowry** [comment]
Maybe I do not understand the PayPal Express Payment system, but I thought that IPN's primary purpose was to verify payment was received.  This serves as a second defense to ensure things are properly updated if the user does not return to the website after completing payment through PayPal.  Without IPN, I think you would have to manually update those orders, and the user would see them as Unpaid until you do so.
