### ISSUE TITLE
Change Duplicate Slug

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#219]
I don't think duplicate product is very clear.  When I select a single product and click duplicate it brings me to the edit page for the item.  If I change the slug it changes the slug for all of the ones that I used the duplicate button with.  It isn't very clear what the duplicates are after I have gotten this far.

If I select multiple products and click duplicate... I can't comprehend what happens.

My understanding of "slug" was that it was supposed to be unique.  If it is not unique how do you guarantee what is put into the cart?

**Comment by jHoldroyd** [comment]
Duplicate product was intended to be used to create product options on a rather basic level, by joining and syncing them we could pull out the information for the varieties. It's a terrible way to do things and in 1.2 this will be changed and duplicate will work as expected without the linking issue.
