### ISSUE TITLE
New installation issue

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#22]
I've just downloaded a new copy of the pugin but when try to install the core I receive this error:

An Error Was Encountered

invalid_fieldtype [add_field]

**Comment by from2day** [comment]
During install there is fieldtype "multiple" on line 173. Should be "relationship". 

File: details.php

**Comment by jHoldroyd** [comment]
That's not correct, it is using a multiple-relationship field rather than relationship (one-to-one) we're using a one-to-many field since products can be in multiple categories.

**Comment by from2day** [comment]
Might be, but after changing type from 'multiple', installation went well.

**Comment by jHoldroyd** [comment]
You're missing the Multiple Relationship field type, which can be gotten from here - https://github.com/parse19/PyroStreams-Multiple-Relationships

**Comment by ChristianGiupponi** [comment]
Maybe you should write it on the readme file because if users use a community version it doesn't know that he need this module :)
By the way on the Pro version of PyroCMS the installation works fine!

**Comment by jHoldroyd** [comment]
We've been using the pro-version so I had no idea it wasn't included with community, this will be reflected in a README change later today.

**Comment by from2day** [comment]
The note :)
http://parse19.com/pyrostreams/docs/field-types/multiple-relationships

I am using community version with PyroStreams module. With added multiple field it works fine.
