### ISSUE TITLE
Product Current Stock Required even when I choose Unlimited

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#220]
Current stock is required even when I choose unlimited.  After I see the error from submission I return and put 0 in there, because we don't hold stock.  It switches the dropdown to "Out of Stock".  This is confusing.

**Comment by jHoldroyd** [comment]
If you set the stock level to 0 and then set it to unlimited it shouldn't attempt to change the dropdown. Admittedly the automatic changing of stock level was added before we had an unlimited stock level but we can't say it's ever been that problematic.

If you really don't want it to do it, it's a simple change in the js/product.js file to remove it.

**Comment by jHoldroyd** [comment]
I've updated the JS a little bit to take this into consideration, changing to unlimited now updates the stock status to 0 so you don't have to worry about setting anything in it.
