### ISSUE TITLE
Plugin method "options" does not exist on class "Plugin_Theme"

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#222]
I'm receiving this error in Pyro log, it happens when I access Firesale front/category: 
Plugin method "options" does not exist on class "Plugin_Theme"

**Comment by jHoldroyd** [comment]
I'll take a look into that and see what's happening.

Thanks for reporting it

**Comment by jHoldroyd** [comment]
I've just gone through all of our error logs to try and find the error in our development servers but I see no reference to it. I'm not sure if it's related to your other issues, but the only thing I can find anywhere about this error is this:

https://www.pyrocms.com/forums/topics/view/17753

Which isn't even about that really. I'm not sure what's causing it, but I don't think it's FireSale and without any way to replicate it there's not much we can do about this one I'm afraid.

**Comment by jHoldroyd** [comment]
I'm going to close this one, I don't believe it's an issue with the FireSale core and may be an issue with your theme or Pyro itself. I can't find any more information on anyone experiencing this bug and after checking error logs we've never seen this before.

If you find any more information or can pin it down to something specifically wrong with this module feel free to reopen it and we'll look into it more for you.
