### ISSUE TITLE
Pyro ENVIRONMENT Constant problem

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#224]
Setting the Pyro ENVIRONMENT constant to a value 'production' will cause that Firesale is not accesable in admin area. It looks for "addons/shared_addons/modules/firesale", but firesale path is "addons/shared_addons/default/modules/firesale"?

A PHP Error was encountered

Severity: Warning

Message: file_get_contents(http://md-filtea.hr/addons/shared_addons/modules/firesale/css/dashboard_productsales.css) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.0 500 Internal Server Error

Filename: libraries/Asset.php

Line Number: 1276

**Comment by jHoldroyd** [comment]
This should be taken care of, just update libraries/firesale in the core and it'll be fixed. Thanks again.

**Comment by zaja** [comment]
Great!
