### ISSUE TITLE
Firesale Search

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#226]
I'm not sure if this is question for Issues, but I can't find any info how to use Firesale Search module? 
I can't see search related route under Routes or any other setting. Also, on Firesale DOCS no info about search module. 
Any guideline guys?

**Comment by jHoldroyd** [comment]
Sorry, we're aware the documentation is really lacking and we're forever working on getting it improved but for now the route you'll need is below and we'll make sure it's added into 1.1.1 so it's installed by default.

```
Map: search/{{ any }}
Route: search(/:any)?
Translation: firesale_search/front/index$1
```

I do have to note though you'll need to be running the next version of FireSale 1.1.1 for this to work, we totally missed search out and the controller names may be different now as it's gone through some changes to bring it inline with the rest of the modules.

I should have that pushed in the next 10 minutes or so.
