### ISSUE TITLE
Subcategory created, but can't edit it

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#227]
I have created sub-category of an root category, but after creation I can't edit it, click on sub-category name in admin area not open edit option in right panel.
Also, How to display sub-category in menu, by default it display only root categories?

**Comment by jHoldroyd** [comment]
I'll look into the editing issues for you soon, could you please provide the details you used for the category information so I can try the same locally and see if it's a special character issue please?

Also about the sub-category display, use the same markup but the plugin tag is:

```
{{ firesale:sub_categories parent=id }}
    ...
{{ /firesale:sub_categories }}
```

You can also do the same with sub_sub_categories. It's all down to limitations with lex not allowing us to use the same plugin name nested, it may have been fixed but I don't think it has so you must use the slightly different name to do it.

**Comment by zaja** [comment]
How exactly sub-category menu works, sub category is available only if parent category is selected?

**Comment by zaja** [comment]
Also, I don't think that this is a special characters issue, if I move it from subcategory to root category it works fine, I can eddit it.
