### ISSUE TITLE
Brands menu not works on front end

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#228]
I have installed Brands module, added some brands and assigned come product to brands. 
I'm not sure why, but Brands menu on front end not works, it display only title "BRANDS", without any brands in list. This is menu code:

{{ firesale:brands limit="0" }}
          <a href="{{ firesale:url route="brand" id=id }}">{{ title }}</a>
{{ /firesale:brands }}

**Comment by jHoldroyd** [comment]
The plugin command for brands is:

```
{{ firesale_brands:get order, limit, etc}}
    {{ title }}<br />
{{ /firesale_brands:get }}
```

If you change that it should work.

**Comment by zaja** [comment]
Thanks, but not sure why it not work, I have entered this:
{{ firesale_brands:get}}
          <li><a href="{{ firesale:url route="brand" id=id }}">{{ title }}</a></li>
{{ /firesale_brands:get }}
