### ISSUE TITLE
Firesale Brands permission

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#229]
It seems that Brands page in admin is not available if user don't have all rights set in permission setting. I have created admin group with limited permissions for Firesale, Brands link is availablem but click on it redirect to Front end index page.

**Comment by chrisnharvey** [comment]
This issue has been around for a while (#81) and will be fixed in v1.2.

The only way (at present) to enable access to the additional FireSale modules is to add them manually to the permissions table in the database.
