### ISSUE TITLE
Problem in Products page with categories

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#23]
hi,
when i add a new product an  I choose a single category ( move the category name from left to right ) and then i try to save it without complete all the information (for example the description) in the category field i have in both the column all the categories.

Example:

http://postimage.org/image/afwd3cfqp/

**Comment by jHoldroyd** [comment]
I think this is a deeper issue with the multiple field type but I've managed to write a little piece of JS that will take care of the display problem. It doesn't save/store all values it just doesn't show the ones you selected however it does know which ones you chose.
