### ISSUE TITLE
Name of product - rename issue

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#230]
I can't edit the name of product if I want to change font case used in Title. it display message that such name already exist.
Example, I have creaed product with this name: PRODUCT 1, if I want to change it to proDUCT 1 firesale will not allow.

**Comment by jHoldroyd** [comment]
I'd say that's more of a streams issue which may turn out to be an issue with MySQL, I don't think there's anything we can do about this one we just rely on the in-built CI and Streams validation.
