### ISSUE TITLE
Empty Cart

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#231]
We would like to create a button that empties the cart.  What is the recommended route to do this?  I see the destroy cart, but I'm not exactly sure that is what we want to do.

**Comment by chrisnharvey** [comment]
You could create a small module which runs `$this->fs_cart->destroy()`. This method completely empties the cart.

**Comment by joshuarlowry** [comment]
We are seeing some strange effects when using this destroy.  If we destroy and then use code immediately after to add items to the cart they don't seem to be showing up.

**Comment by joshuarlowry** [comment]
In addition, does that doestroy the user's session for that load?  It looks like I'm logged out when I visit the cart after calling the destroy.

**Comment by chrisnharvey** [comment]
I see... It shouldn't log you out, however it may now allow you to add stuff to the cart immediately after it has been destroyed. I'll have a look into this and see if there are any problems, if so, I will fix them and let you know.

Could you try the following to empty the cart?:

```
foreach ($this->fs_cart->contents() as $row_id => $item)
{
     $this->fs_cart->remove($row_id);
}
```

**Comment by ghost** [comment]
We have confirmed that destroy works as we expect it to.

Also, the issue we had with the user being logged out was an issue with our code.

This ticket should closed.
