### ISSUE TITLE
Usability - deleting product [request]

### ISSUE THREAD

**Issue by FornetMK** [firesale/firesale#242]
Now - when you delete product - you are returned to the first page of product list. 

That is fine if you have 10 products... but when you delete product from the 600 objects list,  paging back to the page where you have been - is not user-friendly :)

System should remeber the page where you have been before product deleting.

**Comment by jHoldroyd** [comment]
Good call, I'll get this in tonight

**Comment by jHoldroyd** [comment]
There we go, it's now in the 1.2.0/develop branch
