### ISSUE TITLE
Image adding [request]

### ISSUE THREAD

**Issue by FornetMK** [firesale/firesale#249]
Currently you can "drag & drop" image to the field in product edition. 

It is not very user-friendly, unless I do not know how to use it well.  I need to open next window on the computer, with explorer, and drag...

Could we have simple "add images" button, and just select / multiselect images to add from good, old-school "computer explorer" window? Like it is in standard files module of Pyro (you can drag there, but can also choose from standard window)?

**Comment by jHoldroyd** [comment]
We've been considering this for a while, it's annoying at times to say the least. The issue is we have to update the library we use for uploads so it's not a quick or easy fix to make but I'll see what we can do about getting this in for 1.2.0 or 1.3.0

**Comment by jHoldroyd** [comment]
There we go, you can now click to upload and we added fallback for none supported browsers.
