### ISSUE TITLE
We Need Caching Now

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#251]
I thought we could get away with this for longer but as Adam just proved with his crazy menu system, we need this now. Streams does generate a lot of queries as is, but we really don't help things with the way we handle URLs and other things so this must be done now before it becomes too much of an issue.

After some early testing and utilising PyroCache and Codeigniter Cache we reduced a page from 550 queries to 43 in about 10 minutes. This is the aim we need to keep in mind going forward. Just as a note this wasn't a standard site the menu has around 100 categories on every page header and caused a lot of issues.

Not assigning anyone since we need to tackle this together.

**Comment by jHoldroyd** [comment]
Apart from some small tweaks this should be done now, closing.

**Comment by parafas** [comment]
got an issue with apc_fetch() - undefined function... but it is because the APC extension was not installed in the PHP.
more info: http://php.net/manual/en/apc.installation.php

**Comment by jHoldroyd** [comment]
Strange, we set a default and a fallback, if APC isn't found it should switch to using file caching.

If you open up firesale/libraries/firesale.php near the top of the file you'll see a reference to caching with APC and file set. If you change APC to file and give that a shot it should work as a temporary measure while we figure out why it's not defaulting how it should.

**Comment by chrisnharvey** [comment]
I think this issue varies from server to server. For me, CodeIgniter has never been able to correctly detect if it should use the backup adapter, perhaps we should just default to file or allow the admin to change the settings in a config file or in the control panel.

**Comment by parafas** [comment]
changing for file worked fine.
