### ISSUE TITLE
Add Design Controls to Products, Categories, Brands, etc.

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#252]
Something we've come up across recently is wanting different designs for the various categories or products of different types. Rather than hacking something in for each individual product we aim to add JS/CSS, Layout and Template controls to each item that makes sense giving you complete control over how things are displayed.

**Comment by FornetMK** [comment]
Do you mean that it will be possible to style module just like standard pages in Pyro (layouts as files in themes + page layouts defined in admin panel)? That would be really great.

**Comment by jHoldroyd** [comment]
Yes, the ability to choose a range of options including the layout for the page you'd like to use, the template file for this specific page and css/js controls on each of the items we enable them for on a per product/category/etc. basis.

**Comment by jHoldroyd** [comment]
Closing now as this is in and working.
