### ISSUE TITLE
Complete 2.2 Compatibility

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#253]
As 2.2 is nearing release much of the admin styling, labels, etc. have been broken in these later updates. We'll need to go through and ensure everything is working and in place - much of this has already been done at a code level but styling is still off at the moment.

**Comment by FornetMK** [comment]
Well its not as bad  as it looks like, there is some usabitilty issues, but they aren't very annoying, at lest when you explain to the customer whats going on where :) 

I rather feel pain about module not being able to use page layouts coded in the admin panel (unless i dont know how to force it for the module), but this is the case of Pyro itself I think.

Maybe this issue should be be moved to next milestone?

**Comment by jHoldroyd** [comment]
2.2 is now in beta and will be officially released in the next few weeks, we'd prefer to get the compatibility in place now for those that choose to use 1.2.0 before we rip everything apart going to 1.3.0. These changes will be purely cosmetic and will not be changing the functionality to integrate with any of the new systems provided in 2.2 apart from search.

**Comment by jHoldroyd** [comment]
Moving this out of 1.2.0 for now unless we take too much longer this should be fine in 1.2.1 - everything works just styling is a little off now. All languages have been tested and are correct for 2.2.0 but until the styling is finished we can't really work with it.

**Comment by jHoldroyd** [comment]
Closing this as a duplicate.
