### ISSUE TITLE
1.2/develop - Checkout Frontend: on error, form is not repopulated

### ISSUE THREAD

**Issue by osari** [firesale/firesale#255]
When checking out, form fields are not repopulated with values we entered.
To reproduce, enter some values to the form, but leave out the required fields and submit.

Furthermore, "My Billing and Shipping addresses are the same." appears five times under "Shipping Details"

**Comment by jHoldroyd** [comment]
I'll do some testing on this tomorrow and see what we can do to sort it out for release with 1.2.0

**Comment by chrisnharvey** [comment]
I think we've figured out whats going on here. I'll push a fix tonight.

**Comment by jHoldroyd** [comment]
This is now completed in the 1.2 branch, https://github.com/firesale/FireSale/commit/7cc6bb932bb4407e012b075e69f4785b34775205
