### ISSUE TITLE
1.2 - Admin - orders

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#260]
When you check the checkbox on a paid order the bottom option doesn't shows up to allow you to change the order status or to delete it, is it normal?

Problem 2:

When you have an order and with the filter option you try to check different status such as unpaid and you have no order in that status the CP sais that there are no orders and this is ok but if you try to re-open the filter it is impossibile, you need to click on the orders tab to continue.

**Comment by jHoldroyd** [comment]
I'm going to presume problem 1 is a class issue and 2 is a js error that will stop scripts executing...looking into it!

**Comment by jHoldroyd** [comment]
This should be taken care of now https://github.com/firesale/FireSale/commit/cfd12b5cbd9612b32a7749d5107e295cc0e1d209
