### ISSUE TITLE
1.2 - Admin - Products list

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#261]
Maybe the same error is in the 1.1 branch.
When you try to Duplicate or delete a product without check any checkbox the CP allow you to do the action.
In the delete case the CP says "Product delete successfully" when nothing really appened and with the duplicate option it gave a db error.

I think that the best way to handle it is disable the two buttons and enable them only if a checkbox is checked.

**Comment by jHoldroyd** [comment]
I think this is just a simple class name issue and I'll look into it now but also check to ensure that delete/duplicate don't do anything with empty post arrays

**Comment by jHoldroyd** [comment]
Fixed with https://github.com/firesale/FireSale/commit/1d4e63835aaa9163edcb1e3ea42e83da8bf13af3
