### ISSUE TITLE
Can't add product to cart, cannot edit default currency

### ISSUE THREAD

**Issue by motorsiklerider** [firesale/firesale#263]
Stoked on this awesome cms and addon. I am having problems though. I cannot edit the default currency from GBP to USD (Error when saving). Also I cannot add a test product to a cart without getting an error. You can test here if you wish:
http://bulletslinger.com/product/t

I checked file permissions on some files and I couldn't quite tell if that would be an issue. Most look 777?

Just some thoughts, when I installed it on the addon panel, it said it wasn't succesful but it still installed anyway? I doubt that had an effect because it was still installed anyway? I tried searching and couldn't find the issue. Sorry for being a newb!

**Comment by jHoldroyd** [comment]
This is a limitation of Pyro, regardless of what happens with the install, failed or not, it will still class the module as installed. However FireSale should have given you a message telling you what actually went wrong and usually an easy way to fix it. Unless you know what the message was I'd suggest uninstalling and reinstalling and letting us know what it said.

Along with that it would be nice to know your Pyro version, the version of FireSale you were using and the language you tried to install in.

I'm sorry you're having problems though and we'll do what we can to sort it.

**Comment by motorsiklerider** [comment]
Hi, Thanks so much for taking the time to reply. 

I was using pyro's newest release as far as I know and FireSale 1.1 I believe.

I am assuming the installation of pyro or firesale wasn't 100% correct. I deleted everything and did it all again from scratch and now we are in business!

**Comment by jHoldroyd** [comment]
Glad to hear it, closing this now.
