### ISSUE TITLE
Brand Module 

### ISSUE THREAD

**Issue by jerrydread** [firesale/firesale#265]
The brand module in front page, don't display the list, like categories
![categories_list](https://f.cloud.github.com/assets/3247285/60934/527a0636-5c2a-11e2-8ec4-2341821de6b0.jpg)

![brand_list](https://f.cloud.github.com/assets/3247285/60936/628bd9c8-5c2a-11e2-9804-551d01a4afb6.jpg)

**Comment by jHoldroyd** [comment]
To be honest, it's not really meant to. We've never really wanted anyone to use the default views for a site...for a start they're plain awful and are instead meant as a little guide on how to use some of our tags and data objects. We may eventually upgrade the view to include this but it's not really a priority.
