### ISSUE TITLE
Tried to delete a tax band and got an error

### ISSUE THREAD

**Issue by james182** [firesale/firesale#267]
A PHP Error was encountered

Severity: Notice

Message: Undefined property: CI::$taxes_m

Filename: MX/Controller.php

Line Number: 57

Fatal error: Call to a member function can_delete() on a non-object in /Applications/MAMP/htdocs/PyroCMS_Professional_v2.1.5/addons/default/modules/firesale/controllers/admin_taxes.php on line 129

**Comment by jHoldroyd** [comment]
I'm not sure what version you're using but this is now fixed in the 1.2/develop branch by https://github.com/firesale/FireSale/commit/e880b63e997dfb334cb9798c0a18a9dfa85936be
