### ISSUE TITLE
Add attributes tab in product

### ISSUE THREAD

**Issue by ghost** [firesale/firesale#268]
It will be good, if you add this option. And create a customisation attribute field. Thanks in advance

**Comment by jHoldroyd** [comment]
We have something like that running as an additional module but are having a hard time finding a place for it now we can customise everything via streams. It does work well enough for things like product specifications etc that can be unique to each product.

I may clean it up a little bit and finally release it separate or try to package it up with core in a future release.

**Comment by ghost** [comment]
Thanks for that information. Do you have a deadline? Or same beta

**Comment by jHoldroyd** [comment]
It's a little outdated for our 1.2 version and pyro 2.2 but possibly this weekend I'll get a beta in place for trying out

**Comment by jHoldroyd** [comment]
Doing a rewrite on this a bit to get everything updated. Closing this for now but we'll make an announcement when it's ready.
