### ISSUE TITLE
Cart Widget

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#269]
Just gotten a suggestion to add a cart widget which would be very handy to have. Adding this to 1.2.0 as it should be pretty easy to implement.

**Comment by chrisnharvey** [comment]
Nice idea :)

Sent from my iPhone

On 22 Jan 2013, at 12:52 PM, Jamie Holdroyd notifications@github.com
wrote:

Just gotten a suggestion to add a cart widget which would be very handy to
have. Adding this to 1.2.0 as it should be pretty easy to implement.

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/FireSale/issues/269.

**Comment by jHoldroyd** [comment]
Forgot to tag this one, closed with https://github.com/firesale/FireSale/commit/14dad4c1f30cb708ad5437b2985c17f23030fd7f
