### ISSUE TITLE
tax calculation

### ISSUE THREAD

**Issue by parafas** [firesale/firesale#270]
perhaps would be good to have an option to select if the tax is already included in the sale price or not. Because we have difference between both calc. methods.

**Comment by jHoldroyd** [comment]
We've looked at this option a bit today and it just doesn't seem like something we can do with the current system. We may come back to it in a future version but for the time being it's not on the cards. If/when we come back to it I will update this to let you know. Adding it manually may be an option if you really do require it but I can see it require a little bit of hacking.
