### ISSUE TITLE
Currency problem after Save

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#271]
Hi,
I've just created a test site with PyroPro 2.2 and FireSale 1.2-dev but I'm not able to modify currency.
If I edit the Default currency and try to save I receive a "The action you have requested is not allowed."
Is it normal?

No problem if a add a news currency but the errors comes up if I try to edit also the new one

**Comment by jHoldroyd** [comment]
I'll take a look into this now but I have a feeling it'll be related to the other issue you posted

**Comment by jHoldroyd** [comment]
Wrong button when posting sorry!

**Comment by ChristianGiupponi** [comment]
I've just re-downloaded the 2.2 pro and the 1.2 firesale but the error still exists, no problem in creation but error on edit.
You're not able to replicate this error?

**Comment by jHoldroyd** [comment]
I haven't tried to replicate it yet but I know last time I did it on the 2.2 branch it worked but I'll give it a try now and see what I can find out for you.

Edit: Just tried to edit the default which worked, created a new one and edited it and that worked fine too. Could you give me the values of your currency and the changes you're trying to make to it please?

**Comment by jHoldroyd** [comment]
Can I just ask, what are the errors that are coming up? Should have asked that sooner!

**Comment by ChristianGiupponi** [comment]
Just:

An Error Was Encountered [ 500 ]
The action you have requested is not allowed.

**Comment by jHoldroyd** [comment]
Ah, then we should actually have a fix for this one then, did you not enable mod_rewrite on install and are the URLs using index.php?

**Comment by ChristianGiupponi** [comment]
Yes, I use index.php is this the problem?

**Comment by jHoldroyd** [comment]
Yes it is, as @wshatch noted in another issue we haven't enabled CSRF checks in most (all?) of our admin forms which was an oversight and this only causes a problem when you're not using mod_rewrite. It's a simple fix that I'm currently working through now.

**Comment by jHoldroyd** [comment]
Ok so all of our forms are using the correct method for CSRF checks, however because of the url structure of not using mod_rewrite in a number of places the links to get to edit caused it to goto index.phpadmin/ which is what caused the issue. This has been fixed in the last commit and if you update everything should work correctly again.
