### ISSUE TITLE
Save new product issue

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#272]
When I try to save a new product db fails:

Errore del database

Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

SELECT \* FROM `default_firesale_products_firesale_categories` AS `jt` JOIN `default_firesale_categories` ON `jt`.`firesale_categories_id` = `default_firesale_categories`.`id` WHERE default_jt.row_id = 1
Errore del database

Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

UPDATE `default_ci_sessions` SET `last_activity` = 1359191629, `user_data` = 'a:7:{s:8:\"username\";s:5:\"admin\";s:5:\"email\";s:17:\"chri788@gmail.com\";s:2:\"id\";s:1:\"1\";s:7:\"user_id\";s:1:\"1\";s:8:\"group_id\";s:1:\"1\";s:5:\"group\";s:5:\"admin\";s:17:\"flash:old:success\";s:48:\"Il nuovo prodotto è stato aggiunto con successo\";}' WHERE default_jt.row_id = 1 AND `session_id` = '61319a18dc46b303208b9dd1fc3354bf'

**Comment by jHoldroyd** [comment]
How old is the pyro 2.2 install and how old is the firesale 1.2 you're testing on? We've seen that issue before but fixed it a while ago when we first started on 2.2 compatibility. Also try using the multiple field type from our repo rather than Adams.

**Comment by jHoldroyd** [comment]
Another issue that seems to have been sorted by the updated version of the Multiple field type or a newer version of Pyro.

**Comment by yveveke** [comment]
I have a comparable bug.
When you add a product modifier you get the same bug. I use the latest develop version of pyro and firesale.

``` php
A Database Error Occurred
Error Number: 1054

Unknown column 'rel_product.category' in 'field list'

SELECT `default_firesale_product_variations`.*, `cb_users`.`id` as `created_by||user_id`, `cb_users`.`email` as `created_by||email`, `cb_users`.`username` as `created_by||username`, `rel_product`.`id` as `product||id`, `rel_product`.`created` as `product||created`, `rel_product`.`updated` as `product||updated`, `rel_product`.`created_by` as `product||created_by`, `rel_product`.`ordering_count` as `product||ordering_count`, `rel_product`.`code` as `product||code`, `rel_product`.`title` as `product||title`, `rel_product`.`slug` as `product||slug`, `rel_product`.`category` as `product||category`, `rel_product`.`rrp` as `product||rrp`, `rel_product`.`rrp_tax` as `product||rrp_tax`, `rel_product`.`price` as `product||price`, `rel_product`.`price_tax` as `product||price_tax`, `rel_product`.`status` as `product||status`, `rel_product`.`stock` as `product||stock`, `rel_product`.`stock_status` as `product||stock_status`, `rel_product`.`ship_req` as `product||ship_req`, `rel_product`.`description` as `product||description`, `rel_product`.`tax_band` as `product||tax_band` FROM `default_firesale_product_variations` LEFT JOIN `default_users` as `cb_users` ON `cb_users`.`id`=`default_firesale_product_variations`.`created_by` LEFT JOIN `default_firesale_products` as `rel_product` ON `rel_product`.`id`=`default_firesale_product_variations`.`product` WHERE (parent = '1') ORDER BY `default_firesale_product_variations`.`ordering_count` ASC
```

**Comment by jHoldroyd** [comment]
This is the same issue posted here https://github.com/firesale/FireSale/issues/283 and the same applies, as soon as we know more I'll update the other issue.
