### ISSUE TITLE
CSRF issue when editing a product.

### ISSUE THREAD

**Issue by wshatch** [firesale/firesale#274]
Using PyroCMS 2.2dev commit cad18a3dd25c2731812db17c248d02b102b102ed082e
Using Firesale 1.2dev commit b3f47fea7e60303c6169c839076822c3c363fa9f

When I hit "save" on editing a product I get 

An Error Was Encountered [ 500 ]
The action you have requested is not allowed.

Also, there's no CSRF token field in the form.

**Comment by wshatch** [comment]
For some reason, config['csrf_protection'] is set to false when the edit function is called, but set to true when create is called. Any ideas?

**Comment by wshatch** [comment]
Fixed in my latest pull request.

**Comment by jHoldroyd** [comment]
This is a weird one and is not something we've had before but I'll ensure that all forms have protection added just in case. Thanks for pointing it out and as you stated it's fixed I'm presuming it was related to the none-clean URL fix that you posted?

**Comment by jHoldroyd** [comment]
This should be taken care of now with the last commit
