### ISSUE TITLE
Quick Edit is unable to edit price

### ISSUE THREAD

**Issue by wshatch** [firesale/firesale#275]
Firesale 1.2dev commit b3f47fea7e60303c6169c839076822c3c363fa9f
Pyrocms 2.2dev commit cad18a3dd25c2731812db17c248d02b102ed082e

Every field except price is able to be edited in quick edit.

**Comment by jHoldroyd** [comment]
I'll look into this one in a moment, quick edit is due to get a few updates very soon to fix a few other known issues and inconsistencies.
