### ISSUE TITLE
Editing a product right after creating a product gives me a DB error

### ISSUE THREAD

**Issue by wshatch** [firesale/firesale#276]
Using PyroCMS 2.2dev commit cad18a3dd25c2731812db17c248d02b102b102ed082e
Using Firesale 1.2dev commit b3f47fea7e60303c6169c839076822c3c363fa9f

Getting this database error when I try to edit a product after saving. Might have something to do with the fact that I haven't created any categories yet.

A Database Error Occurred
Error Number: 1054

Unknown column 'category' in 'field list'

UPDATE `default_firesale_products` SET `code` = 'foo', `title` = 'amazing items', `slug` = 'amazing-items', `category` = NULL, `rrp` = '21.00', `rrp_tax` = '20.000', `price` = '10.50', `price_tax` = '10.000', `status` = '1', `stock` = '10', `stock_status` = '1', `ship_req` = '1', `description` = 'afadfsdfsdfsdf', `tax_band` = '1', `shipping_weight` = NULL, `shipping_height` = NULL, `shipping_width` = NULL, `shipping_depth` = NULL, `brand` = NULL, `updated` = '2013-01-27 23:17:13' WHERE `id` = '2'

**Comment by jHoldroyd** [comment]
Category doesn't exist as a field in the products table and I have a feeling the latest updates to streams continue to break the multiple field type that we use for it. I'll have a look into this issue but could you make sure you're using this version of it https://github.com/firesale/PyroStreams-Multiple-Relationships

**Comment by jHoldroyd** [comment]
After some testing of newer versions and the updated multiple field type this seems to be fixed now.
