### ISSUE TITLE
Cannot add "category" while creating product in pyrocms 2.2

### ISSUE THREAD

**Issue by prashanna** [firesale/firesale#281]
I have just installed FireSale 1.2dev in PyroCMS 2.2.0-rc2 and tried to create product but I cannot choose category for the product. Drag and drop is not working.

Also the dropdowns in the admin menu are disabled from create product page.

**Comment by jHoldroyd** [comment]
Chances are there's a few JS errors being thrown that will just be stopping this stuff in 2.2 now. We've been holding off on finally doing our compatibility because we thought we had it three times now and more things kept changing with streams to break FireSale. As we're close to a release though we'll be taking care of this remaining issues and getting compliant in the next few days.

**Comment by jHoldroyd** [comment]
Just checked and this was indeed related to the multiple field type which has been fixed by Adam

**Comment by prashanna** [comment]
Thanks a lot

**Comment by nikescar** [comment]
This issues is not cleared.
I have installed firesale on pyrocms 2.2.1
I try to install with firesale 1.2-devlop, 1.2-master, 1.2.2(on pyrocms repo), 1.3-develop.
none of them are working.
I also try to update multiple field types to 2.0.1 on all of tries. and it did not help.

the issue looks like derived from send category data to multiple field type in product create view.
but I cannot find what exactly problem is. could you help me to find the issues?

**Comment by AJSturrock** [comment]
Hi @nikescar 

Are you getting any JS errors at all on the product create view?

**Comment by nikescar** [comment]
Hi, Andy. Thank you for your reply.

http://i.imgur.com/lWwHJVi.png

yes, it does have JS errors.

do you have any idea, how to fix this?

**Comment by AJSturrock** [comment]
Looks like the js files are not found. Check they exist in the right directory and the path matches? If not grab a copy and save them to the right place.

Hope this helps!

**Comment by nikescar** [comment]
Thank you for your help. I made patch. but I don't think it is good practice for every use.

so I put it as a patch here.

https://gist.github.com/nikescar/5844419

run patch from multiple field type dir. then it will load appropriate css and js from firesale multiple field_types dir.

thank you for your help, again.
