### ISSUE TITLE
Save a new product same issue as #272

### ISSUE THREAD

**Issue by BrainCatcher** [firesale/firesale#285]
I'm new to Github (learning). And i expect you aren't paying attention to closed issues. So i opend a new issue. Excuse me in advance if this is annoying, it is not meant to be  :)

Just having PyroCMS 2.2.0 PRO installed with a fresh zip file from this repo. Saving a new product still triggers the following error:

A Database Error Occurred
Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

SELECT \* FROM `default_firesale_products_firesale_categories` AS `jt` JOIN `default_firesale_categories` ON `jt`.`firesale_categories_id` = `default_firesale_categories`.`id` WHERE default_jt.row_id = 1

A Database Error Occurred
Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

UPDATE `default_ci_sessions` SET `last_activity` = 1362778639, `user_data` = 'a:7:{s:8:\"username\";s:5:\"admin\";s:5:\"email\";s:20:*************\";s:2:\"id\";s:1:\"1\";s:7:\"user_id\";s:1:\"1\";s:8:\"group_id\";s:1:\"1\";s:5:\"group\";s:5:\"admin\";s:17:\"flash:old:success\";s:36:\"A new product was added successfully\";}' WHERE default_jt.row_id = 1 AND `session_id` = '1df42dda36092ada309b2b73b0a7b124'

**Comment by jHoldroyd** [comment]
Hi it's not a problem, and we welcome issues being reported, it really helps. Before looking into this could you please grab the latest version of the multiple field type (https://github.com/adamfairholm/PyroStreams-Multiple-Relationships/archive/2.0/develop.zip) and replace your existing one to see if that fixes it. It looks like that may be the issue as we've seen it before or something very similar .

If that doesn't take care of it just let us know and I'll look into it for you.

**Comment by BrainCatcher** [comment]
I installed the recommended files by adamfairholm. The module conflicts with the allready existing module in Pyro Pro. It is standard distributed with Streams. So i commented the whole scriptfile 'field.multiple.php' located in 'system/cms/modules/streams_core/field_types/multiple/'. After that, the modified streams  module by adamfairholm is working like it's supposed to, like adding new products and modify them.

I hope i made things clear enough, feel free asking questions. At the moment i'm exploring Github functionality. Recently i translated the language into dutch. I asume that  forking  this repo and make a pull request will do the trick and contribute to this project. Right? I will find it out though :)

**Comment by BrainCatcher** [comment]
ah, now i know what this function does,, didn't meant close this issue that quick :)

**Comment by jHoldroyd** [comment]
Yeah the issue is the version distributed probably hasn't been updated with the latest fixes that were added in the past week or so to make it compatible with 2.2. Glad to hear the issue is taken care of for you though.

And yeah you can just fork the repo, start making changes and submit them as a pull request. If you did translate firesale we'd love to include it. Just as a note though a lot of the language files were updated today and your versions may be slightly out of date. If you do submit it as a PR I'll go through and add in the missing entries with # translate after the new items.

**Comment by yveveke** [comment]
I think you have to mention this on the installer or something. We get daily reports of this bug.
Think of my poor mailbox. :smile:

**Comment by jHoldroyd** [comment]
Oh I know! Chris is writing a check into the installer to make sure they're running the correct version of multiple...it's getting a bit much now and we're either going to release 1.2.2 specifically for this issue or retag 1.2.1 with this fix in.
