### ISSUE TITLE
Bug - (After Edit Products) CMS 2.2 / 1.2-dev

### ISSUE THREAD

**Issue by ghost** [firesale/firesale#286]
A Database Error Occurred
Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

SELECT \* FROM `default_firesale_products_firesale_categories` AS `jt` JOIN `default_firesale_categories` ON `jt`.`firesale_categories_id` = `default_firesale_categories`.`id` WHERE default_jt.row_id = 1

**Comment by jHoldroyd** [comment]
Duplicate, see https://github.com/firesale/FireSale/issues/285 for a fix.
