### ISSUE TITLE
Product modifier error

### ISSUE THREAD

**Issue by yveveke** [firesale/firesale#287]
I downloaded the latest build, and when you add a product modifier you get this error : The Parent Category field is required.

**Comment by jHoldroyd** [comment]
Any chance you could do a trace on the Ajax URL using something like firebug or httpfox? By the sounds of it the script isn't passing in the parent ID in the URL as it should and this is stopping the required data being assigned into POST. So if you could find the URL and data you're sending over (and anything it returns) that would really help us debug the cause.

**Comment by yveveke** [comment]
When I open the dialog it loads this url

``` php
Request URL:http://domain/admin/firesale/products/modifier/1?csrf_hash_name=b9aa94868ed880e30098e64fc772396e
Request Method:GET
Status Code:200 OK
```

When I press 'Save' the Ajax loads

``` php
Request URL:http://domain/admin/firesale/products/modifier/1
Request Method:POST
Status Code:200 OK

Form data:
csrf_hash_name:b9aa94868ed880e30098e64fc772396e
type:1
title:test
instructions:
btnAction:undefined
```

I think it's because the btnAction is undefined. it sets the parent variable when btnAction has Save as value.

**Comment by jHoldroyd** [comment]
That does seem to be the issue, I'm not a fan of how I set that value in our modal forms but it seemed to work at the time but it's not reliable enough. I'll get an alternative method put together and get a push fixed asap.
