### ISSUE TITLE
Reordering categories does not rebuild their slugs

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#288]
After the changes made to slugs to make them unique they now must be updated on reorder to give them their correct values if they are moved to a new parent etc.

**Comment by yveveke** [comment]
Any update on this? All child categories are not shown in the admin atm.

**Comment by jHoldroyd** [comment]
They should be, the only thing this affects is the URL the slug has after its been reordered, can you upload a screenshot of your category page and post a link? I'm interested to see if the issue is what I think it is.

**Comment by yveveke** [comment]
These images expire in 3 days ...

This is what it needs to be
http://awesomescreenshot.com/03a11o5f37

This is what it becomes after you save and/or come back to the categories page.
http://awesomescreenshot.com/09c11o2q31

**Comment by jHoldroyd** [comment]
Yeah the images are missing, there SHOULD be plus and minus signs next to those bars that have children that lets you expand them down. If you try clicking the area next to them it should dropdown, it helps to inspect element and check it's there and that the uls have children.

For some reason during one commit the images were corrupted and on some servers/browsers they don't display anymore. I'm trying to dig up a backup to restore them from.

**Comment by yveveke** [comment]
I wanted to say, that it wasn't the case because the children li's were not there when I inspected it in Chrome.
But when I went to make a screenshot to show you, the categories work as expected.

My backoffice spooks.

**Comment by yveveke** [comment]
![less](https://f.cloud.github.com/assets/3223937/259283/a43c6742-8cb9-11e2-8987-10f6c26a4215.png)
![more](https://f.cloud.github.com/assets/3223937/259284/a4513302-8cb9-11e2-8f07-c991d5c91ebe.png)
![on](https://f.cloud.github.com/assets/3223937/259285/a46bad7c-8cb9-11e2-8b12-fd4c59519074.png)
![off](https://f.cloud.github.com/assets/3223937/259286/a46b9472-8cb9-11e2-8d45-0dd74e5766a7.png)
