### ISSUE TITLE
Shipping doesn't appear in checkout process

### ISSUE THREAD

**Issue by yveveke** [firesale/firesale#289]
Like the title says, i made a shipping option, but it doesn't show in the checkout process.

**Comment by chrisnharvey** [comment]
Hi,

Did you get the minimum/maximum price and weight? If so, is your shopping cart total within those ranges?

Chris

**Comment by yveveke** [comment]
I only filled in a shipping price.

**Comment by yveveke** [comment]
Indeed when I fill in a price range or a weight range, it appears in the checkout.
But then the list labels in the admin are not correct, it says up to unlimited when you don't fill in a range.

And a small error : In the admin, when you enter a value it doesn't append .00 automatically. When you submit the form without it, it gives an error.

**Comment by yveveke** [comment]
It seems an additional error : I filled in the ranges in the admin, the shipping selection appears in the checkout proces. I select it, but the shipping price doesn't get added.
