### ISSUE TITLE
No address in admin order edit

### ISSUE THREAD

**Issue by yveveke** [firesale/firesale#291]
The address fields are empty when you open an order.
url : http://domain/admin/firesale/orders/edit/1#ship

Also, a minor one, while you're at it. The layout of the fields can be improved.

**Comment by jHoldroyd** [comment]
I'll look into this now and agree that the forms look terrible in orders with 2.2

**Comment by yveveke** [comment]
Thanks for the layout update.

The fields are still empty though : http://awesomescreenshot.com/03911t06bc
Even though an address is submitted in the database

**Comment by jHoldroyd** [comment]
If the address isn't pre-selected in the drop-down then it isn't being found for the selected user, are you sure there was an address set as some items don't require shipping and will not have been set during checkout?

**Comment by yveveke** [comment]
Shipment selection during checkout : http://awesomescreenshot.com/09111t4wc7
Payment process (no shipment is calculated, reported in another issue and you'll see that the address is filled in but not saved as an adress) : http://awesomescreenshot.com/0af11t4pc1

**Comment by yveveke** [comment]
When you fix the shipment price thing, you can close this issue of mine "Shipping doesn't appear in checkout process"

**Comment by yveveke** [comment]
I already see the problem for why the order address fields are not filled in.
The ID that you use in your JS is not the same as in the html.

``` php
<select name="ship_to" id="ship_to-firesale_addresses-firesale_addresses" class="chzn hidden chzn-done" style="display: none;">
<option value="">-----</option>
<option value="1" selected="selected">Office</option>
</select>
```

And JS

``` js
// Change address
    $('#ship_to, #bill_to').change(function() {
        var pre = $(this).attr('id').replace('_to', '');
```

Plus the admin theme changes all select fields with the chosen library : http://harvesthq.github.com/chosen/

The reason why the shipment price is not shown is still unknown.

**Comment by yveveke** [comment]
I got the shipment price bug partially fixed.

front_cart.php Line 602

``` php
$order['price_tax']     = $order['price_total'] - $order['price_sub'] - $order['price_ship'];
```

becomes

``` php
$order['price_tax']     = $order['price_total'] - $order['price_sub'] - $order['shipping']['price'];
```

front_cart.php Line 608

``` php
$order['price_ship']    = $this->currency_m->format_string($order['price_ship'], $this->fs_cart->currency(), FALSE);
```

becomes

``` php
$order['price_ship']    = $this->currency_m->format_string($order['shipping']['price'], $this->fs_cart->currency(), FALSE);
```

front_cart.php Line 722

``` php
$order['price_ship']    = $this->currency_m->format_string($order['price_ship'], $this->fs_cart->currency(), FALSE);
```

becomes

``` php
$order['price_ship']    = $this->currency_m->format_string($order['shipping']['price'], $this->fs_cart->currency(), FALSE);
```

Here lies the fix to save the shipping price in the database. But $this->firesale->roles['shipping'] is always NULL
front_cart.php Line 338

``` php
if ( $data['ship_req'] AND isset($this->firesale->roles['shipping']) AND isset($input['shipping'])) {
```

I really need to learn how to commit bug fixes on Github...

**Comment by jHoldroyd** [comment]
Yeah it would be much easier for all of us if you did it as a PR.

But to shed some light on your issue, roles has been ripped out and will always be null now. It was replaced with an event based system which you can find further down the file.

**Comment by ChristianGiupponi** [comment]
A quick method to send pull requests are to clone the repo, edit your copy files and save them.
Once done just click on the topo of your page to "pull request" or something similiar and you're done :)

**Comment by yveveke** [comment]
Just tried a commit with the official github Mac app. Don't see it on the website though ...

**Comment by yveveke** [comment]
@jHoldroyd  "It was replaced with an event based system which you can find further down the file."
Sorry, but I don't find it. Don't really know what to look for :cry:

**Comment by jHoldroyd** [comment]
I'm looking into it now, it's going to take a bit more of a rewrite than I initially thought. Hopefully I'll have something done soon

**Comment by jHoldroyd** [comment]
Closing this as I just fixed it, there is still a larger issue at hand though with shipping options missing...and I still have NO idea why your dropdown has an id of ship_to-xxx...we'll have to investigate that too. As for this, it's now done.
