### ISSUE TITLE
Cart Rewrite

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#296]
Our shopping cart is a bit of a mess, and is built upon the CodeIgniter Shopping Cart.

I am starting a rewrite of the FireSale shopping cart as a PSR-2 package.

**Comment by huglester** [comment]
Wow chrisnharvey. That seems like a challenge!
Does it mean it will be accessible from different frameworks?

**Comment by chrisnharvey** [comment]
That is correct yes, sorry for the delayed response, I've only just seen this. I will be using the moltin/cart package which I wrote recently.

**Comment by chrisnharvey** [comment]
This is a duplicate of #358. Closing.
