### ISSUE TITLE
FireSale Upgrade to 1.2 with Pyro 2.1.5, error?

### ISSUE THREAD

**Issue by enlivenapp** [firesale/firesale#301]
Hi Guys,

I upgraded to the new FireSale release and was immediately greeted with the below when I clicked on FireSale in the addon.  I haven't dug in yet just reporting it.

_

A Database Error Occurred
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders`' at line 2

SELECT SUM(i.`qty`) AS `count`, SUM(i.`qty` \* i.`price`) AS `sales`, date_format(i.`created`, `"%Y-%m")` AS `month` FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders` AS o ON `o`.`id` = `i`.`order_id` WHERE `o`.`order_status` IN (2, 3, 4) AND date_format(i.`created`, "%Y-%m") > '2012-03-24' GROUP BY `month` ORDER BY `month` asc LIMIT 12

Filename: /home/nelaonli/public_html/addons/shared_addons/modules/firesale/models/dashboard_m.php

Line Number: 51
_

**Comment by jHoldroyd** [comment]
I've just ran that query and it's totally fine when it's put through PMA. What version of MySQL are you using?

**Comment by enlivenapp** [comment]
I'm running MySQL 5.1.68-cll

**Comment by jHoldroyd** [comment]
I'll have to grab an older version and see what we can do about getting it to work on older versions of MySQL. The issue is though the query is built via the usual db methods available and not just written manually.

**Comment by jHoldroyd** [comment]
Ok I've just tested the query on MySQL 5.1.41 and it ran without issue again so I have no idea why on 5.1.68 it wouldn't. Could you try copying the query and running it within PMA or directly on the command line and see if it still gives you an error? It's a valid query according to the 8 versions we've tried it on now and I'm not sure what's going on with this

**Comment by enlivenapp** [comment]
Response from PMA:

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders`' at line 1

I tried a fresh run at the query (IE, not copying it from above):
SELECT SUM(i.`qty`) AS `count`, SUM(i.`qty` \* i.`price`) AS `sales`, date_format(i.`created`, `"%Y-%m")` AS `month` FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders` AS o ON `o`.`id` = `i`.`order_id` WHERE `o`.`order_status` IN (2, 3, 4) AND date_format(i.`created`, "%Y-%m") > '2012-03-25' GROUP BY `month` ORDER BY `month` asc LIMIT 12

Same in command line.
mysql> SELECT SUM(i.`qty`) AS `count`, SUM(i.`qty` \* i.`price`) AS `sales`, date_format(i.`created`, `"%Y-%m")` AS `month` FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders` AS o ON `o`.`id` = `i`.`order_id` WHERE `o`.`order_status` IN (2, 3, 4) AND date_format(i.`created`, "%Y-%m") > '2012-03-25' GROUP BY `month` ORDER BY `month` asc LIMIT 12;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders`' at line 1

I thought it might have been a missing comma after month: AS `month` FROM... but that fails also.

Looks like I'm the winner of the Super Obscure code bug award for this week.  :/

**Comment by jHoldroyd** [comment]
What happens if you remove the brackets around the join query?

**Comment by enlivenapp** [comment]
I'm sure this is semantics...  I don't have any brackets.

**Comment by enlivenapp** [comment]
AH!!

Error:
SELECT SUM(i.`qty`) AS `count`, SUM(i.`qty` \* i.`price`) AS `sales`, date_format(i.`created`, `"%Y-%m")` AS `month` FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders` AS o ON `o`.`id` = `i`.`order_id` WHERE `o`.`order_status` IN (2, 3, 4) AND date_format(i.`created`, "%Y-%m") > '2012-03-25' GROUP BY `month` ORDER BY `month` asc LIMIT 12

Shows results
SELECT SUM(i.`qty`) AS `count`, SUM(i.`qty` \* i.`price`) AS `sales`, date_format(i.`created`, "%Y-%m") AS `month` FROM (`default_firesale_orders_items` AS i) INNER JOIN `default_firesale_orders` AS o ON `o`.`id` = `i`.`order_id` WHERE `o`.`order_status` IN (2, 3, 4) AND date_format(i.`created`, "%Y-%m") > '2012-03-25' GROUP BY `month` ORDER BY `month` asc LIMIT 12

Difference:
Error: date_format(i.`created`, `"%Y-%m")` AS

Results: date_format(i.`created`, "%Y-%m") AS   

Removed backticks from "%Y-%m")

Mike

**Comment by enlivenapp** [comment]
Looks like active records is the culprit.  It's adding the backticks in an odd spot in relation to the actual query.

// Build initial query
        $query = $this->db->select("SUM(i.`qty`) AS `count`, SUM(i.`qty` \* i.`price`) AS `sales`, date_format(i.`created`, \"$format\") AS `{$type}`")

**Comment by jHoldroyd** [comment]
What happens when you pass in FALSE as the second param for the select?

**Comment by enlivenapp** [comment]
So, I know a bit about MySQL, but I'm not super well versed in it.  If you don't mind, send me the full query you'd like me to run?

email in plain text is fine: sales at wild blue chicken dot com

**Comment by jHoldroyd** [comment]
I just mean if you change your select to be: 

$this->db->select("SUM(i.qty) AS count, SUM(i.qty \* i.price) AS sales, date_format(i.created, \"$format\") AS {$type}", false)

What happens? This will stop it escaping automatically and may fix your issue, the same goes for most of the other db functions for example false as a where's 3rd param will stop escaping

**Comment by enlivenapp** [comment]
That works.

However, with the upgrade, "FireSale" is no longer in my dashboard (I can only access it from the Addons page) and the sub-roles are not listed in the permissions (the check boxes are there, but there's no labels)...  This may end up being some weird upgrade issue.

I'm going to do a fresh install on Pyro 2.1.5 and see if it's a code issue or upgrade issue.

Mike

**Comment by enlivenapp** [comment]
OK.  On fresh install of firesale on Pyro 2.1.5 pro

Notices: 
1: Your currently installed version of the Multiple field type is out of date, please delete or upgrade it before attempting to use FireSale  (not shown when I upgraded)
2: The module "firesale" has been installed.

Same database error(above) and the link to Multiple field types (in Firesale 1.1master readme doc) is broken. just fyi.  Although I did find where you posted a new link: https://github.com/adamfairholm/PyroStreams-Multiple-Relationships/tree/master

adding FALSE to the select statement shows the dashboard again (and was properly populated with data) w/o DB errors.

however, "FireSale" is still missing from the admin navigation but can be accessed through addons and 

Users/permissions shows: FireSale : [] [] [] [] [] [] [] [] [] []   <-- no labels for check boxes.
Settings/FireSale appears to be correct.

**Comment by jHoldroyd** [comment]
I have a terrible feeling they're missing because in 2.2 they changed the format used for permissions meaning we'll have to add duplicate entries into the language files to cover it. I'll figure something out and get a fix pushed.

I'll also get the false put into the core too, it works on the current DB version I'm running so it should be good to go global.

**Comment by jHoldroyd** [comment]
I've added the false as standard and fixed the permissions language files in ca9a3d82adf1750711221c6a2f28962b0c70031c
