### ISSUE TITLE
Error editing product in 2.2 Pro

### ISSUE THREAD

**Issue by johnwarlick** [firesale/firesale#303]
I added some categories and then added a test product but got this error on edit. Using the 2.2 compatible version from the addon store with a 2.2 pro copy of PyroCMS.

A Database Error Occurred

Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

SELECT \* FROM `default_firesale_products_firesale_categories` AS `jt` JOIN `default_firesale_categories` ON `jt`.`firesale_categories_id` = `default_firesale_categories`.`id` WHERE default_jt.row_id = 1

**Comment by jHoldroyd** [comment]
See #285 the issue is caused by an out-dated multiple relationship field type. You can either upgrade your core field type, or delete it and let it fall back to the correct version included with firesale
