### ISSUE TITLE
Modifier Pricing not working as expected

### ISSUE THREAD

**Issue by chusting** [firesale/firesale#308]
I have just installed the latest firesale module v1.2 (downloaded for pyrocms.com as well as github) with pyrocms 2.2 (professional).

I am running into unexpected behaviors with modifier pricing.

Admin:
1. When I attempt to add a variation price, the modal to add the variation never goes away (until I manually close it). 
Along with that, it appears to add multiple products to the "product list" (as many times as you hit submit on the modal, it will add that many copies of the product). 
Upon deleting the newly added product, I am able to view and edit the variation price.
2. When I attempt to add a "Single Product" modifier, I am never presented with a list of existing products, rather it appears and functions similar to how the variation price is intended to work.

Site:
1. When I attempt to add a product to the cart with a modifier selected, the cart and checkout do not reflect the price difference for the modifier selected.
- If the modifier is a "variation" the cart does not add the product at all;
- If the modifier is a "single product" the cart appears to start with the single product price as entered in the modifiers, but overrides the final price with the starting product price.

If I recall, the "single product" pricing is built to override the product base price as a lump sum price (but I may not be correct in saying that). Either way, are there any plans to build the "single product price" as an add-on to the base price of the product as opposed to a price override (or possibly have that as an option when adding the modifier)? 

I could see this working either as a straight price add-on or a multiplier (qty \* single product price)?  

I am hoping to dig deeper into the code later this afternoon, but I figured I would get it out there to see if you had any input!

Thanks!

**Comment by jHoldroyd** [comment]
I'll go through the various issues raised here and see what's intended and what isn't before trying to make any fixes.

**Comment by chusting** [comment]
Thanks Jamie,

Sorry I ran out of time over the weekend to look into this further, but
hope to dig in deeper when I get a chance, I just figured I would bring it
up for your reference.

Thanks again, and have a great week!
Curt Husting

**Comment by chusting** [comment]
Hi Jamie,

Any chance you had time to look into this? I finally have some more time available, but didn't want to troubleshoot if you had already done so... Let me know.

Thanks!
Curt

**Comment by jHoldroyd** [comment]
We just haven't found the time yet sorry, if you want to look into it and add a PR that'd be fantastic.

**Comment by chusting** [comment]
Will do, thanks for the update

**Comment by jHoldroyd** [comment]
Just to clear some things up, the Single Product modifier is intended to be for things like Gift Wrapping where you want to add an option that isn't a separate product.

**Comment by jHoldroyd** [comment]
This should all be fixed now with a range of changes we've made. The pricing is still in addition to the parents price rather than it's total price but we may add that as an option in the future. If you run into any more of these issues in the latest development build just create a new issue for each problem you're having and we can manage that easier for you.
