### ISSUE TITLE
Product Quick Edit bug

### ISSUE THREAD

**Issue by treerunner** [firesale/firesale#309]
Latest FireSale 1.2 dev.. Pyro 2.2

Quick Edit not submitting on products. I can get it to submit by removing in admin_products.php:

if ( $post['btnAction'] == 'save' ) {

.. but it then has a cache issue and doesn't display the updated row.

**Comment by jHoldroyd** [comment]
Two different issues, one was pretty easy to sort (I was using the wrong variable) and the cache issue seems to be that without a redirect the cache isn't truly cleared. I split it up into two ajax queries so it is correctly cleared now as it should be and the interface is updated with the new data.

**Comment by treerunner** [comment]
Thanks!!
