### ISSUE TITLE
Add the ability to set multiple locations for gateways

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#314]
Instead of having a single path for FireSale gateways, it would be nice to have a way to add gateway paths so we can store payment gateways anywhere. We could also include views for each gateway instead of storing these in our core views path.

**Comment by chrisnharvey** [comment]
Tell a lie, this isn't quite done. I still need to update gateways.php

**Comment by jHoldroyd** [comment]
Should be done now
