### ISSUE TITLE
Sub Category Database Error

### ISSUE THREAD

**Issue by treerunner** [firesale/firesale#316]
Sub-category pages are throwing a database error for me.

This displays OK:
/category/freezer/

but this throws error:
/category/freezer/meat/pork/

A Database Error Occurred

Error Number: 1066

Not unique table/alias: 'default_def_page_fields'

SELECT `default_def_page_fields`._, `cb_users`.`id` as `created_by||user_id`, `cb_users`.`email` as `created_by||email`, `cb_users`.`username` as `created_by||username`, `profiles`.`display_name` as `created_by||display_name`, `default_def_page_fields`._, `cb_users`.`id` as `created_by||user_id`, `cb_users`.`email` as `created_by||email`, `cb_users`.`username` as `created_by||username`, `profiles`.`display_name` as `created_by||display_name` FROM `default_def_page_fields`, `default_def_page_fields` LEFT JOIN `default_users` as `cb_users` ON `cb_users`.`id`=`default_def_page_fields`.`created_by` LEFT JOIN `default_profiles` as `profiles` ON `profiles`.`user_id`=`default_def_page_fields`.`created_by` LEFT JOIN `default_users` as `cb_users` ON `cb_users`.`id`=`default_def_page_fields`.`created_by` LEFT JOIN `default_profiles` as `profiles` ON `profiles`.`user_id`=`default_def_page_fields`.`created_by` WHERE `default_def_page_fields`.`id`=5 AND (`default_def_page_fields`.`id`='1') ORDER BY `default_def_page_fields`.`created` DESC, `default_def_page_fields`.`created` DESC LIMIT 1

Can anyone duplicate this or is it only me?

**Comment by jHoldroyd** [comment]
That doesn't look like it's got anything to do with FireSale to be honest. You may want to check your routes though as that seems to be a page error rather than a category.

**Comment by treerunner** [comment]
Yes, it's a page error upstream from FS. I'm using default routes that came with FS. I'll see if I can figure it out. thanks much.

**Comment by treerunner** [comment]
Just to follow up: same error on a brand new PyroCMS 2.2 / Firesale install. still looking..

**Comment by jHoldroyd** [comment]
It'll be a routes problem directing you to pages where the error actually is (I presume). I think we'll need to update the defaults going forward to ensure the new url structure for categories is correct.

**Comment by jHoldroyd** [comment]
This is definitely an issue with the page it's going to when it doesn't hit the category, closing now.

**Comment by prashanna** [comment]
I have same kind of issue.
/categories/furniture is working fine but
/categories/furniture/sofas is not working. it shows "page missing"
How can i access sub-categories.

**Comment by AJSturrock** [comment]
In the FireSale routes try changing the category route to this

Map: categories/{{ slug }}{{ any }}
Route: categories(/[a-z0-9-_/]+)?(/[0-9]+)?
Translation: firesale/front_category/index$1$2

Working example:
http://demo.getfiresale.org/store/clothing/tops

**Comment by prashanna** [comment]
Thank you Adam that worked for me
