### ISSUE TITLE
Adding price of product without "tax link" not working correctly

### ISSUE THREAD

**Issue by jurajdurajka** [firesale/firesale#328]
FireSale v1.2.1 (base, with no additional modules)

Situation: I'm trying to assign a price to a product (either during creation of new or during editing of an existing one), and click on the "unlink" button, so that I can enter different values of the price before and after tax.

When I then enter any values and click on Save, the price before taxation shown in this edit form gets changed according to the price after taxation (asi if I haven't "unlinked" them before). The price in the shop, on the other hand, is the price before taxation plus tax.

In the database, correct values are present.

The issue is the same with RRP and Current Price.

In the attached images, the Tax Rate is set to 20.00.
before saving:
![before_save](https://f.cloud.github.com/assets/3853808/391711/d3d38e3c-a76b-11e2-877b-c83485c4ef52.png)
after saving:
![after_save](https://f.cloud.github.com/assets/3853808/391714/df415448-a76b-11e2-8a3f-b458a56f95e4.png)
products list in admin
![products_admin](https://f.cloud.github.com/assets/3853808/391716/e7239360-a76b-11e2-848c-5a1f948071c1.png)

**Comment by jHoldroyd** [comment]
I've just removed the code for tax linking, it was a nice feature to have but it's a remnant of our old code and since 1.1.0 when tax bands were introduced it just hasn't worked and nor could we easily make it work again.
