### ISSUE TITLE
Categories plugin 

### ISSUE THREAD

**Issue by jerrydread** [firesale/firesale#329]
Hi there, 

The plugin works, but has a issue, when i click on child, uri display page missing instead of product details....

see example below:

![firesale-categories](https://f.cloud.github.com/assets/3247285/391994/615c7492-a773-11e2-9b35-757a17d1e268.jpg)

regards...

**Comment by jHoldroyd** [comment]
This is actually a route issue, it requires a / in the regex now. This will be added on reinstall or you can manually add it via routes.
