### ISSUE TITLE
Error Adding Product Attribute

### ISSUE THREAD

**Issue by shaneneal** [firesale/firesale#330]
When adding an Attribute to a product if you type in the select attribute box and click add to add a new one a Not Found error is given.

**Comment by jHoldroyd** [comment]
We've had a few issues with the way we add attributes, it seemed like a cool way to do it but it's causing more problems than it's worth now and we're going to redo that part of the attributes module. Should have it done tomorrow in preparation of the 1.2.2 release

**Comment by shaneneal** [comment]
Great

**Comment by jHoldroyd** [comment]
We've kept it as normal but this should have been fixed, it seems to have been an issue with certain setups and subdomains/none-rewriten urls
