### ISSUE TITLE
Products filter in Orders admin not working + error messages are stacking

### ISSUE THREAD

**Issue by jurajdurajka** [firesale/firesale#332]
FireSale v1.2.1 (base, no additional modules installed)

In the Orders section, when I click on any product in product filter, I only get a message
`There are currently no orders`
even when there actually are orders containing this product. 

Moreover, these error messages are stacking and they never disappear - screenshot attached: 

![orders](https://f.cloud.github.com/assets/3853808/396314/b2baf10a-a81e-11e2-9e77-925686179b6d.png)

**Comment by yveveke** [comment]
In the products section you have an equal error.
The only option that works is the category. All the others give "Product successfully deleted" even though it didn't.

edit : never mind, it seems that I have to update my version of Firesale.

**Comment by jurajdurajka** [comment]
Allright, so the problem with Products dropdown not working in Orders admin is probably because of this:
file _orders_m.php_ , function **add_filters**

``` php
case 'product':

      // Get possible IDs
      $query = $this->db->select('order_id')->where('product_id', $query)->group_by('order_id')->get('firesale_orders_items')->result_array();
```

should be

``` php
case 'product':

      // Get possible IDs
      $query = $this->db->select('order_id')->where('product_id', $value)->group_by('order_id')->get('firesale_orders_items')->result_array();
```
