### ISSUE TITLE
Name of Taxes stream in DB is lang:firesale:sections:taxes

### ISSUE THREAD

**Issue by jurajdurajka** [firesale/firesale#333]
FireSale v1.2.1 (base, no additional modules installed)

Probably because of this (details.php):

``` php
public function taxes($method = 'add')
    {
        if ($method == 'add') {
            $this->streams->streams->add_stream('lang:firesale:sections:taxes' ...
```

(I know these bugs should be pull requests, but I have absolutely no time now, sorry)

**Comment by jHoldroyd** [comment]
It's not a problem, thanks for catching them and sorry there's so many minor issues!

**Comment by jHoldroyd** [comment]
Closed with the latest commit
