### ISSUE TITLE
Install erro firesale 1.2 master pyro 2.2 master

### ISSUE THREAD

**Issue by ribsousa** [firesale/firesale#335]
Ocorreu um erro de base de dados
Error Number: 1366

Incorrect string value: '\xE9 um s...' for column 'desc' at row 1

INSERT INTO 'default_firesale_gateways' ('created', 'desc', 'enabled', 'name', 'ordering_count', 'slug') VALUES

**Comment by jHoldroyd** [comment]
What language were you installing with?
