### ISSUE TITLE
Setting default currency doesn't seem to take effect

### ISSUE THREAD

**Issue by mbbender** [firesale/firesale#338]
Upon creating a currency of USD, setting it as the default via value 'USD' and disabling GBP, currency is being set as NULL and is falling back to id of 1 in mulitple locations where currency is trying to be called from session data, which is GBP.

**Comment by jchamberlain** [comment]
I just started trying out FireSale and am having the same (or similar) problem. It appears that currency id 1 is hardcoded in multiple places, so adding or changing currencies doesn't really do much, even if you disable GBP. As the code stands, the best way to use a different currency is to rename GBP and change it's formatting.

**Comment by jHoldroyd** [comment]
The currency setting was a remnant of a pre-currency era and was left in place for some reason. Thanks to @jchamberlain this has now been fixed and upon updating to 1.2.2 you should see your options in the dropdown and the system will now correctly check.
