### ISSUE TITLE
Dutch Ideal gateway

### ISSUE THREAD

**Issue by jaapjolman** [firesale/firesale#339]
Hey guys

could you also integrate the dutch main gateway by using api called mollie?

**Comment by jHoldroyd** [comment]
It's not something were really familiar with to be honest. You're more than welcome to prepare something yourself to use or even PR it into the core but it's not really something we can do for you unfortunately.

**Comment by jaapjolman** [comment]
but its is a ci-merchant thingy name mollie

https://github.com/expressodev/ci-merchant/tree/master/libraries/merchant
there is a merchant_mollie.php which is the one i need but it is not on the one your use
