### ISSUE TITLE
Filter products in Admin

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#34]
When I try to filter products by category I run into a SQL error:

Error Number: 1054

Unknown column 'category' in 'where clause'

SELECT `default_firesale_products`.\* FROM `default_firesale_products` WHERE (category=3) ORDER BY `default_firesale_products`.`id` DESC LIMIT 30

Filename: /Applications/MAMP/htdocs/PyroCMS_PRO/modules/streams_core/models/row_m.php

Line Number: 505

**Comment by jHoldroyd** [comment]
Working on this at the moment but it's not an easy one with the Multiple field type being a little buggy, might have to go back to the drawing board and rewrite the query - dropping get_entries for the admin dashboard.

**Comment by jHoldroyd** [comment]
Should finally be fixed and also extended the functionality quite a bit to allow for requests such as stock_status and even price if needed, just use the url format of:

/admin/firesale/products/FIELD NAME/VALUE

And it should work, the only exception is category which has to be handled differently to the rest but still uses the same format.
