### ISSUE TITLE
$.getJSON in orders.js are missing SITE_URL

### ISSUE THREAD

**Issue by jurajdurajka** [firesale/firesale#342]
FireSale v1.2.1 with no additional modules

In _orders.js_, there are few lines like this:

``` javascript
$.getJSON('/admin/firesale/orders/ajax_address/' ...
```

I guess these need to be like this:

``` javascript
$.getJSON(SITE_URL+'/admin/firesale/orders/ajax_address/' ...
```

(it has caused some problems in my project while adding products manually into orders, changing shipping address etc)

**Comment by jurajdurajka** [comment]
Also, the pictures in the create order->products admin tab are referenced directly like this

``` htm
<img src="/files/thumb/<?php echo $product['image']; ?>
```

**Comment by chrisnharvey** [comment]
You're right yes, we'll get this sorted ASAP.

Sent from my iPhone

On 3 May 2013, at 11:23 AM, Arxi notifications@github.com wrote:

FireSale v1.2.1 with no additional modules

In _orders.js_, there are few lines like this:

$.getJSON('/admin/firesale/orders/ajax_address/' ...

I guess these need to be like this:

$.getJSON(SITE_URL+'/admin/firesale/orders/ajax_address/' ...

(it has caused some problems in my project while adding products manually
into orders, changing shipping address etc)

—
Reply to this email directly or view it on
GitHubhttps://github.com/firesale/firesale/issues/342
.
