### ISSUE TITLE
Pyrocache used incorrectly in some places

### ISSUE THREAD

**Issue by jurajdurajka** [firesale/firesale#343]
FireSale v1.2.1 base with no additional module

I've noticed usage of pyrocache like this: ( _admin_orders.php_, function **index()**)

``` php
// Get filter data
        $users    = $this->pyrocache->model('orders_m', 'user_field', array(( $type == 'created_by' ? $query : NULL), $this->firesale->cache_time));
```

If I understand it correctly, the last parameter should be a parameter of the _pyrocache->model()_ function, not a parameter of _orders_m->user_field()_ function. Therefore the array() has its ending bracket in the wrong place and it should be: 

``` php
// Get filter data
        $users    = $this->pyrocache->model('orders_m', 'user_field', array(( $type == 'created_by' ? $query : NULL)), $this->firesale->cache_time);
```

This appears in a few more places, just search for 
" _firesale->cache_time))_ "
to find them.

Correct me if I'm wrong or if this has already been corrected, I use the old v1.2.1.

**Comment by jHoldroyd** [comment]
The reason for this is we (stupidly) automated the addition of pyrocache to all of our models with a regex pattern that did well enough but it caused issues with extra brackets within the array. We cleared most of the issues up but we missed those ones so thanks for caching them. I did a wider search for the same issue and cleaned up a few in products too.
