### ISSUE TITLE
adding product to manual order in backend

### ISSUE THREAD

**Issue by shaneneal** [firesale/firesale#346]
when creating an order from the back and an trying to add a product to that order it comes up with not found.
this was 1.2.2.

**Comment by AJSturrock** [comment]
I've not been able to replicate this on the latest 1.2.2 version, can you provide any other details on this?

**Comment by shaneneal** [comment]
i can email you logins for the site its happening on it was a fresh install of pyro 2.2 the lastest pro 

and 1.2.2-dev.

**Comment by jHoldroyd** [comment]
If you're still having this issue could you please send those login details to support@getfiresale.org and one of us will look into it for you

**Comment by CameronGilroy** [comment]
I'm getting the same problem with the 1.2/master.
On the first click it gives a 404 error then it appears to calls the correct file (a json file).
`URL_1: http://editbox3.local/admin/firesale/orders/ajax_add_product/1/1/1?csrf_hash_name=a4783722a5398c62d149f1416adb417f`
`URL_2: http://editbox3.local/tpcode.com-pyro//admin/firesale/products/ajax_product/1?csrf_hash_name=a4783722a5398c62d149f1416adb417f`

**Comment by CameronGilroy** [comment]
I've found out what is the problem! The install needs to be in the base domain and not in a folder. See the difference between url 1& 2. I fixed it by moving it to the base domain.

**Comment by jHoldroyd** [comment]
Thanks for that, from there I noticed that we'd missed a url constant from the second ajax call so anyone using a sub-directory would have issues. Fixed now though and sorry we missed it!
