### ISSUE TITLE
adding category

### ISSUE THREAD

**Issue by shaneneal** [firesale/firesale#347]
when adding a new category the existing category list doesn't refresh on save, and show the new category. this was on dev -1.2.2

**Comment by AJSturrock** [comment]
This sounds like a caching issue. The cache should be cleared when a new category is created from the admin panel. Try clearing your cache and see if this resolves the problem.

**Comment by jHoldroyd** [comment]
That's not the issue, this is a newly introduced problem with categories being saved using ajax rather than a page refresh any changes made to the type are not reflected in the left-hand sortable list. It's on my list of things to look into and fix though.
