### ISSUE TITLE
Error messages when I click on Orders and Gateways -Fresh installation

### ISSUE THREAD

**Issue by yaadspace** [firesale/firesale#35]
1. When click on Orders, i get the error:
   An Error Was Encountered
   invalid_stream [get_stream]
2. When I click on gateways, I get an error:
   A Database Error Occurred
   Error Number: 1146

Table 'yawdspac_biblesociety.default_firesale_gateways' doesn't exist

SELECT \* FROM (`default_firesale_gateways`)

Filename: /home1/yawdspac/public_html/yaadspace2/bible/addons/default/modules/firesale/libraries/gateways.php

Line Number: 63

**Comment by ChristianGiupponi** [comment]
Are you using the PyroCMS Community version? Try to install this module: https://github.com/parse19/PyroStreams-Multiple-Relationships
This shoul fix the first error

**Comment by yaadspace** [comment]
I am using the community Version and I have the latest version of pyroStreams installed.

**Comment by from2day** [comment]
yaadspace, "Multiple Relationships" is installed as additional field type.

**Comment by jHoldroyd** [comment]
It doesn't come with the Community version by standard, but you can download it from the link above. The failed install caused the mysql errors, closing this for now.

**Comment by hsq** [comment]
Just have to open it... I have installed PyroCMS 2.1.4 pro. The field type is existing... 
The error when installing the firesale module 1.1:

An Error Was Encountered
invalid_stream [get_stream]

**Comment by wrximpreza** [comment]
A have the same problem 
PyroCMS 2.1.5
Firesale 1.1
https://github.com/parse19/PyroStreams-Multiple-Relationships -  I install

An Error Was Encountered
invalid_stream [get_stream]

Log:
ERROR - 2012-11-06 20:05:19 --> invalid_stream [get_stream]
ERROR - 2012-11-06 20:05:31 --> invalid_stream [get_stream]

**Comment by ChristianGiupponi** [comment]
Your Control Panel is set in English or another language?

**Comment by wrximpreza** [comment]
I found the problem. Not set a table in the database. They did not set. Here's the problem.
An Error Was Encountered
field_slug_in_use [add_field]

PyroCMS 2.1.5
Firesale 1.1
https://github.com/parse19/PyroStreams-Multiple-Relationships - I install

**Comment by ChristianGiupponi** [comment]
I think you need to do a full uninstall of all the FireSale's modules and reinstall it.
Maybe sometihing goes wrong during the first installation and try to set the Control Panel language to english to see if everything goes well

**Comment by wrximpreza** [comment]
Did what you wrote but the error remains
An Error Was Encountered
field_slug_in_use [add_field]

**Comment by jHoldroyd** [comment]
Did you have a failed install previously to this and did you try to uninstall it correctly first? This issue generally crops up when someone deletes firesale or some database tables but doesn't remove all of the stream references and then tries to reinstall.

If you did go into the database and try to manually remove tables you'll need to delete all references to firesale_\* from default_data_fields and default_data_fields_assignments

**Comment by robbiek** [comment]
I am also getting this issue.

An Error Was Encountered [ 500 ]
field_slug_in_use [add_field]

latest version of pyrocms community edition installed and the latest develop branch of firesale installed.
