### ISSUE TITLE
Can't add product to cart when using Modifiers of type Variation

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#351]
When using Variation type Modifiers it and submitting the add to cart form the product never appears in the cart. I haven't investigated why this happens as i am not familiar with the cart system.

Input and Single product types appear to work fine.

**Comment by jHoldroyd** [comment]
How are you trying to insert it and which version of FireSale are you using?

**Comment by iknowfoobar** [comment]
I am using the latest 1.2-dev pulled from github yesterday evening. As I am just learning how Firesale works everything I have done so far is pretty much out of the box.

Here is a product I have created with Colour Variations
http://pyrocms.giles.superrb.pro/product/product-1

When I add the product it never appears in the basket, I can try to debug if you could point me in the right direction?

**Comment by iknowfoobar** [comment]
I see this is probably a duplicate of https://github.com/firesale/firesale/issues/308

**Comment by jHoldroyd** [comment]
I'm looking into it now but I'm not sure it's a duplicate, more than likely it's an issue with a commit made sometime this week that changed the way we add items to the cart.

**Comment by jHoldroyd** [comment]
I think I managed to replicate this, any chance you can update your copy with the latest version in 1.2/develop and let me know how it goes please

**Comment by iknowfoobar** [comment]
Merged your update, unfortunately I still can't add products that use the Variation Type Modifier.

Do I need to rebuild the product at all?

**Comment by jHoldroyd** [comment]
Can I just ask, what are the stock level, stock status and status of your variation products? Sounds stupid but they each have a these values, independent of the parent and as such may not be what you think they are. For instance one could be draft, one could be out of stock, etc etc. If they're out of stock then they won't be added to the cart and this could be the issue.

It may not be the problem but I'd like to rule it out since we've not really seen anything like it before is all.

**Comment by iknowfoobar** [comment]
![screen shot 2013-05-23 at 14 27 38](https://f.cloud.github.com/assets/255807/554588/adc17a94-c3ac-11e2-9d77-03bb7aa80535.png)

See attached for how I created the variations. They all appear to by live, and in stock.

I have noticed however that if I use any of the filters on the admin products page the parent product doesn't show in the list. It doesn't matter which filter or what I set the filter to it never shows.

I can provide admin access to my dev site if that helps?

**Comment by iknowfoobar** [comment]
Just tried completely removing the all firesale modules and reinstalling them. So I am using it straight out of the box and I still have the same problem :(

**Comment by jHoldroyd** [comment]
Without having access to the scripts to properly debug it's going to be difficult. I'll get a fresh install going later and see if I can replicate and avoid having to do that.

**Comment by iknowfoobar** [comment]
I have identified where the issue is occurring however before I delve further and try to work out why it is happening I thought I would get your opinion.

In `Front_cart::insert()` on line 189 there is an `if()` statement:

``` php
if ( $product != FALSE and ( $product['stock_status']['key'] == 6 OR $qty > 0 ) and
                    ( ! isset($modifiers['type']['key']) or ( isset($modifiers['type']['key']) and $modifiers['type']['key'] != '1' ) ) )
```

it would appear that this is failing as for any product with a variation type modifier the `$modifiers['type']['key'] == 1`

I don't know what this check is for but does pointing it out mean anything to you?

**Comment by jHoldroyd** [comment]
There's a few different checks in there to do different things. There's checks to stop parent products (those with variations) being inserted into the database, the reason for this is they're just a container for their children. So on insert/post we figure out which version you actually want and make the necessary changes to the post data before getting there. It also does multiple checks on stock levels to ensure all options are available to you.

So that being there isn't necessarily the problem because before that point it's switched out for the correct product. If that's not happening then that's where the issue is.

**Comment by iknowfoobar** [comment]
OK, I think I am understanding you. So the $product that is found should be child product not the parent one?
I have just checked now and that seems to be correct, it is finding the child and not the parent.

I can see in the modifiers property for the product that the parent_id is correct too. It just seems to be this type attribute in the modifiers property which is set to 1 and therefor failing those checks. If I remove that part of the check the child product is added to the cart and I am able to purchase it fine.

**Comment by iknowfoobar** [comment]
So is the check on the type correct, if so then I guess it is being set incorrectly somewhere else?

**Comment by jHoldroyd** [comment]
I thought we were able to replicate this issue but it turned out to be a badly themed version of the modifier_form.php file causing a very similar issue. But the default version is correct so we're back to square one unless for some reason yours is wrong too but there's currently no variation products to be able to check on.

**Comment by iknowfoobar** [comment]
I have added variations to one of the products and it is still happening. 

Not sure how you guys aren't seeing it. I am using a clean install of PyroCMS Pro 2.2.1 and a clean install of Firesale 1.2.2-dev and left the default theme on.

Does the same on several servers and my local machine so it doesn't seem to be an environment thing. Is the add the cart form set up correctly in the out of the box templates?

**Comment by jHoldroyd** [comment]
It appears to be, we've now tested with the default theme on 8 different servers, 6 different versions of PHP and still nothing coming up. I've just done another clean install of 2.2.1 of Pyro Community and 1.2.2-dev of FireSale, trying to replicate your screenshot exactly and it worked out of the box. I'll do another clean install of Pyro Pro and give that a try but I'm not exactly sure what to tell you at this point.

**Comment by iknowfoobar** [comment]
Hmm, well thanks for trying. If you check my version now I have var_dump the product on the cart insert method so you can see what is being loaded and attempted to add to the cart if that is any help?

I will also try it with Pyro Community too and see if I get the same problem with that.

**Comment by iknowfoobar** [comment]
I think I may have found something odd. Your check tries to see if $modifiers['type']['key'] doesn't exist and allow the product to be added if it doesn't. For my products this value doesn't exist if I just dump out the $modifiers variable but does exist if I check for it. I am seeing the following which is odd and I am not sure is correct:

``` php
var_dump($product['modifiers']['type']['key']); // null
$modifiers = current($product['modifiers']);
var_dump($modifiers['type']['key']); // string '1' (length=1)
var_dump($modifiers['type']); // string '1' (length=1)
```

How can a string be an array at the same time? Am I missing something here?

**Comment by iknowfoobar** [comment]
That was slightly wrong:

``` php
var_dump($product['modifiers']['type']['key']);
```

should have been

``` php
var_dump($product['modifiers'][0]['type']['key']); // string '1' (length=1)
```

Still I shouldn't be seeing an array being a string at the same time should I or have I just been using Symfony for so long I have forgotten how arrays work?

**Comment by iknowfoobar** [comment]
I can confirm that I have the same problem with the Community edition too
http://pyrocmscommunity.giles.superrb.pro/product/product-1

**Comment by iknowfoobar** [comment]
I think I have fixed the issue by detecting whether or not the $modifiers['type'] is actually an array before trying to determine the value of one of it's elements.

Works great for me, I can now add variants to the cart and purchase them. The stock level of the variant has decreased. I assume this is normal behaviour?

I am going to submit a pull request with this update.
