### ISSUE TITLE
Could not install the module.

### ISSUE THREAD

**Issue by yckart** [firesale/firesale#356]
I get an error if I try to install FireSale. I walked through the step by step instructions in docs:
- [x] PyroCMS 2.2.1 Community
- [ ] Multiple Relationships Field Type 
- [x] FireSale modules uploaded to  `addons/default`

However, I'm able to install the module in backend, but not succesfully. It just say **Could not install the module.** and in the `log`-folder is nothing to see...

By the way, I'm working on a local-machine (uWamp), is it maybe possible that the problem sits here?

Do I miss something?

**Comment by jHoldroyd** [comment]
Try the latest dev version in shared addons rather than default, if that doesn't work try adding break points to the installation process in details.php to figure out which section is having a problem. Without more information there's not much else we can do for you at the moment.
