### ISSUE TITLE
Can't Create Order from admin

### ISSUE THREAD

**Issue by james182** [firesale/firesale#36]
I tried to create an order from the admin and i get this.

---

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: libraries/Fields.php

Line Number: 144

---

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: libraries/Fields.php

Line Number: 390

---

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: libraries/Fields.php

Line Number: 391

**Comment by jHoldroyd** [comment]
Should be fixed now
