### ISSUE TITLE
Order Receipts

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#361]
I am not sure if I have missed it, but does firesale support email order receipts?

For example once the purchase is complete is a summary of the order sent to the customer, or do you rely on the payment gateway to send the receipt?

**Comment by jHoldroyd** [comment]
Yes it does, you can see the templates we use in the structure/email templates section of admin.

**Comment by iknowfoobar** [comment]
Excellent, found it thanks, I hadn't set up my SMTP settings on my dev server which is why I wasn't receiving them and was searching through the code for where they might be :)
