### ISSUE TITLE
Upload more photos at once option #2

### ISSUE THREAD

**Issue by huglester** [firesale/firesale#365]
Hello everyone,

we can upload many photos at a time: admin/firesale/products/edit/1/#images
when Drag and Drop.. but when click- only one file can be selected.

Is it a limitation of HTML5 ? And only Flash can allow this option?

Thank you

**Comment by jHoldroyd** [comment]
The fallback method was simply missing the multiple flag which is now added and the scripts already handle the action so nothing else needed changed. Sorry this wasn't already done.

**Comment by huglester** [comment]
no problem. thanks. tested. works!

**Comment by huglester** [comment]
@jHoldroyd one more question.. is there any way so we can limit (for example) to 1 upload at a time?

I spotted that if we start to upload many images at the same time, order gets swapped because one images get uploaded faster than others... Any way around this?

Thanks

**Comment by jHoldroyd** [comment]
Firstly if you refresh the page when uploads are done (we're working on making this work without the need to do this) you can drag and drop your existing images to reorder them.

If you still want to limit them check js/upload.js and near the start of that file you'll find a variable called maxfile, just set it to 1. The file is minified so it may be a little difficult to do but that's where it is.
