### ISSUE TITLE
Front-End Payment bug

### ISSUE THREAD

**Issue by james182** [firesale/firesale#37]
When clicking the Submit & Pay button you get to this URI "cart/payment" and you get this error:

---

A PHP Error was encountered

Severity: Warning

Message: str_word_count() expects at least 1 parameter, 0 given

Filename: plugins/helper.php

Line Number: 206

---

**Comment by jHoldroyd** [comment]
That's due to the address changes made last night, I'll update the theme later today but for now you can replace the payment.php, payment_complete.php and addresses.php files in the theme with those from the default views which are updated to match the new field.
