### ISSUE TITLE
Extra pages are not visible in pages-tree

### ISSUE THREAD

**Issue by yckart** [firesale/firesale#371]
Don't know what happened there, but the extra pages like _"Category"_, _"Product"_, _"Cart"_... are not visible in the pages-tree (not the navigation-tree). The "funny" thing is, that if I open them directly e.g. `http://localhost/cart`, the page exists.

The problem is not that the pages are not visible, rather than that If i create the pages manually I can't change its page-slug...

Any ideas how to get them create in real or how to _"re-build"_ them?

**Comment by AJSturrock** [comment]
Hi yckart,

Modules in pyro have their own views (pages) that are separate from regular pyro pages. If you wish to change the layout and contents of FireSale views you can do so in your theme. To overload the default views copy the module view files from addons/shared_addons/modules/firesale/views to addons/shared_addons/THEMENAME/modules/firesale. From here you can alter the views however you want.

You can also change the slug to these pages by heading over to firesale->routes in the admin panel. e.g. changing /cart to /basket

For more info see here: https://www.pyrocms.com/documentation/2.0/theming-pyrocms/overloading-module-views

Hope this helps,
Adam

**Comment by yckart** [comment]
@AJSturrock Yeah, I have already thought of something like this! Thanks for the respond...

**Comment by yckart** [comment]
@AJSturrock Changing _cart_ to _foo_ results in `404` and after changing back to _cart_ results even in `404`... (Rebuilding the routes doesn't affect that)

**Comment by AJSturrock** [comment]
@yckart 

You can check what the routes are inside system/cms/config/routes.php FireSale routes should be at the bottom of the file between two comments. Also check whats stored in the database and the values match.

The cart route (as foo) should be:

map: foo{{ any }}
route: foo(/:any)?
translation: firesale/front_cart$1
Enable HTTPS: no

Working example: http://demo.getfiresale.org/foo

Thanks,
Adam

**Comment by yckart** [comment]
Ok, the route was not taken to the database. Works now, thanks! :)
