### ISSUE TITLE
Column 'created_by' in where clause is ambiguous Error

### ISSUE THREAD

**Issue by jromey** [firesale/firesale#372]
Running Pryor version 2.2.1 and on the front end when going to cart/checkout, I receive the following error:  

A Database Error Occurred

Error Number: 1052

Column 'created_by' in where clause is ambiguous

SELECT `default_firesale_addresses`.*, `cb_users`.`id` as `created_by||user_id`, `cb_users`.`email` as `created_by||email`, `cb_users`.`username` as `created_by||username`, `profiles`.`display_name` as `created_by||display_name` FROM `default_firesale_addresses` LEFT JOIN `default_users` as `cb_users` ON `cb_users`.`id`=`default_firesale_addresses`.`created_by` LEFT JOIN `default_profiles` as `profiles` ON `profiles`.`user_id`=`default_firesale_addresses`.`created_by` WHERE (created_by = '1' AND title != '') ORDER BY `default_firesale_addresses`.`id` DESC

**Comment by AJSturrock** [comment]
Hi @jromey 

Are you running the latest version of FireSale (1.2.2)? This should have been fixed. If your version is not the latest would you be able to upgrade and see if the problem persists?

Thanks,
Adam

**Comment by jromey** [comment]
Downloaded 1.2.2 and it appears to be working much better now.  Thank you.
