### ISSUE TITLE
Categories Plugin

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#376]
I have just pulled all changes from the last 2 weeks (been away on holiday) and the categories plugin appears to be broken now. I can't get it to output anything sensible now.

Using the out of the box example:

```
{{ firesale:categories parent="0" }}
  {{ if parent == id }}
<li>
  <a href="{{ firesale:url route="category" id=id }}"><strong>{{ title }}</strong></a>
  <ul>
  {{ firesale:sub_categories parent=id }}
    <li><a href="{{ firesale:url route="category" id=id }}">{{ if category.id == id }}<strong>{{ title }}</strong>{{ else }}{{ title }}{{ endif }}</a></li>
   {{ /firesale:sub_categories }}
   </ul>
</li>
  {{ else }}
<li><a href="{{ firesale:url route="category" id=id }}">{{ title }}</a></li>
  {{ endif }}
{{ /firesale:categories }}
```

it always outputs

``` html
<li> 
  <a href="http://example.com/category/"><strong></strong></a> 
  <ul> 
    <li><a href="http://example.com/category/"><strong></strong></a></li> 
  </ul>
</li>
```

no matter what your category structure is. Has something changed does the documentation need to be updated?

**Comment by AJSturrock** [comment]
Hi Iknowfoobar,

In the latest dev version we have changed all plugins to return {{ entries }} rather than just an array of products. This is so you can do:

`{{ if entries }}
Some title or other content {{ entries }} categories {{ /entries }}
{{ else }}
no entries!
{{ endif }}`

We'll be updating the docs and examples for all the plugins shortly.

There's a forum post on this subject https://www.getfiresale.org/forums/topics/view/39

Thanks,
Adam

**Comment by iknowfoobar** [comment]
Thanks for the response, however I still can't get this to work when sub categories are used, I just get LEX parse errors if I try to use any of the sub_categories or sub_sub_categories methods?

**Comment by AJSturrock** [comment]
Hi Iknowfoobar,

Just a quick update, I'm rolling these changes to the category methods back as looping through additional arrays is causing further lex bugs. It'll be reverting back to the old method without {{ entries }}.

Thanks again,
Adam

**Comment by iknowfoobar** [comment]
Cheers Adam, thanks for the swift action as we are currently working on 2 projects with Firesale!

**Comment by iknowfoobar** [comment]
Is the products plugin going to be reverted too, if so do you have an eta on it?

**Comment by AJSturrock** [comment]
I'll look into if there are any issues with the products plugin returning {{ entries }}

It might be the case that using the products plugin (or any plugin for that matter) that returns {{ entries }} multiple times on a page causes a similar issue.

Thanks again

**Comment by AJSturrock** [comment]
The products plugin will return {{ entries }} as there are no further issues. The concern I had above is not the case and you may use the products plugin on a page as many times as you like. I have made one quick fix though to ensure the plugin cache keys are unique for products and categories. https://github.com/firesale/firesale/commit/ad5929792cd29fd197948768db3f1bc879cdf092

**Comment by iknowfoobar** [comment]
Excellent, thanks
