### ISSUE TITLE
Sub Title for Products

### ISSUE THREAD

**Issue by alexborton** [firesale/firesale#377]
Hi guys, 

I would like to request an (optional) Sub Title for products. This will help with constructing index pages with item details before click-through. 

Is this something that could be developed?

Thanks

**Comment by AJSturrock** [comment]
You can add custom fields with streams or through the streams interface (if you have pyrocms pro). 

Here's an example to add fields with streams
https://gist.github.com/AJSturrock/5858170

Thanks again,
Adam

**Comment by iknowfoobar** [comment]
Thanks Adam, I work with Alex, I am still getting my head round the streams system, where would we use that example code?

We are using community but have the streams manager installed. The products don't appear in this manager, only streams created via the manager seem to appear there.

Thanks again
Giles

**Comment by AJSturrock** [comment]
You can run the code anywhere and just run it once. The install function in a custom module is also a good place.

**Comment by alexborton** [comment]
Cheers Adam - Giles has managed to install extra fields.
