### ISSUE TITLE
Product Image not showing

### ISSUE THREAD

**Issue by alexborton** [firesale/firesale#378]
Hi,

It seems that the Product image is not showing in a firesale:products loop. 

I have tried the example code on the site and some more basic versions, but there seems to be no recognition for the {{ image }} tag.

Here is an example of my code;

{{ firesale:products category=page:product_category_id limit="3" }}
  {{ entries }}
{{ if image }}
            {{ image }}
        {{ else }}
            {{ theme:image file="no_image.png" alt="No Image" }}
        {{ endif }}
    <article class="single-product">
        {{ title }}
        {{ price_formatted }}
    </article>
  {{ /entries }}
{{ /firesale:products }}

I am aware that that would just output the image ID and not the image - this is just a demo of my usage.

All the other items are showing as they should.

**Comment by AJSturrock** [comment]
Hi Alex,

Have you tried clearing your cache and double checking the products in question have at least one image each. I've double checked and this should be working as you stated.

You may want to update your plugin file to the latest version as there have been a few fixes implemented today and see if this resolves the issue.

Thanks,
Adam

**Comment by alexborton** [comment]
Hi Adam, 

We have a staging and development server setup - both running identical databases.

Since posting, i checked the staging server to find the ID's were being output. I can also see the ID's on my development server, but only for some products (where all the product image ID's show on the staging server). 

I have tried clearing my cache several times, but still no ID's on some products! Seems to be some kind of caching issue. 

Do you have any suggestions?

Thanks

**Comment by AJSturrock** [comment]
You could try and var_dump the entries just before the return in the firesale/plugin.php and see if you can see the images in there.

I would also check the products with no images showing in the admin panel on your development server to double check that the images are actually uploaded and attached.

Thanks again

**Comment by alexborton** [comment]
Hi Adam,

I did the var_dump and there were no images attached to the items. (although clearly they were in the backend, and visible!).

I deleted the image of one of the items and added a new image. This seemed to fix all of the images that were not being output... Very strange. 

Thanks

**Comment by jHoldroyd** [comment]
Image (I think) will only return a single images ID, the primary. There should be an images array in there somewhere though

**Comment by AJSturrock** [comment]
Seems like a caching issue if after an upload/delete all the images are now shown.

**Comment by AJSturrock** [comment]
Closing this, as it looks like the product data was from the cache

**Comment by BhimAle** [comment]
I have multiple product image and need to show it on the front-page. I can only show one image in front-page... how can i show my all image product in front-page ?
