### ISSUE TITLE
Shipping option not available if From and To (weight and price) left empty

### ISSUE THREAD

**Issue by alexborton** [firesale/firesale#382]
The Shipping option will only become available in the checkout if the From and To weight and price fields are filled in. 

Neither of those field are required. If they are not filled in, they should default to numbers to cover all products (0.00 - 9999999.99).

Cheers

**Comment by chrisnharvey** [comment]
You're right! If you leave them blank then this should make them _unlimited_.

I'll look into this for you.

**Comment by alexborton** [comment]
Cheers Chris.

I have another one for you..! (sorry!).

The 'Go to Checkout' button on the cart does not work on IE7.

Cheers!
Alex

On 30 June 2013 17:50, Chris Harvey notifications@github.com wrote:

> You're right! If you leave them blank then this should make them *
> unlimited*.
> 
> I'll look into this for you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/firesale/firesale/issues/382#issuecomment-20250259
> .

## 

_Alex Borton_
Web Developer

## Superrb Studio

Studio. +44(0) 2392 637971
Twitter. @superrbstudio http://twitter.com/superrbstudio

## Facebook. facebook.com/superrb http://www.facebook.com/superrb

## Hayling Island

## http://www.superrb.com

**Comment by jHoldroyd** [comment]
Chances are because it's a button that has a name and value, IE7 doesn't support this (afaik) and is most likely causing the issue. Have you tried including the html5 shiv and seeing if that helps?

**Comment by AJSturrock** [comment]
Fixed in 437986c111
Leaving min and max price/weight blank will mean the cart contents will not be checked against this value when deciding which shipping options to display.
