### ISSUE TITLE
Install Errors with Fs 1.2.2 on Pyro2.2.1Pro

### ISSUE THREAD

**Issue by ikoniqoz** [firesale/firesale#389]
OK - I have moved up to PyroCMS 2.2.1 for this project and have installed FS 1.2.2 OK as well as the Design module.
When I visit the FireSale Dashboard I get greeted by what you see in this: http://d.pr/i/QNbI  

I have MySQL 5.5.21, PHP 5.3.5 installed on Win7 dev system.

Anyone else experience this ?

**Comment by AJSturrock** [comment]
fixed in 8f97ae3

**Comment by pavoltanuska** [comment]
This "fix" caused error - all dashboard divs are now empty.

"<?=" doesn't mean "<?php" but it is short for "<?php echo"

So all lines affected in commit 8f97ae3 lack "echo"

**Comment by AJSturrock** [comment]
Cheers, I've added this now, was half asleep when I made the previous commit! Looks like we made the fix at the same time, thanks though!
