### ISSUE TITLE
An other installation issue

### ISSUE THREAD

**Issue by MarceauKa** [firesale/firesale#40]
Hi !

I've got a problem with the 0.9.7 version of FireSALE on a fresh install.

This is the error that I've got :

"An Error Was Encountered

invalid_fieldtype [add_field]"

I've tried on the Community version 2.1.2 with "Multiple Relationship" and the Community version 2.1.2 with "PyroStreams 2.2-dev".

What's going on ?

**Comment by chrisnharvey** [comment]
Hi,

Where did you add your multiple relationship field?
- Chris

**Comment by MarceauKa** [comment]
addons -> shared_addons -> field_types -> multiple -> field.multiple.php, [...]

**Comment by yllumi** [comment]
I think it's about read permission to those files.

**Comment by chrisnharvey** [comment]
Are you still having this issue?

**Comment by yllumi** [comment]
I think it is not a problem to close the issue.

**Comment by jHoldroyd** [comment]
I'll close it due to a lack of response, if permissions are changed and you still experience the issue please re-open this with more information.
