### ISSUE TITLE
Editing products

### ISSUE THREAD

**Issue by james182** [firesale/firesale#42]
i can't edit products now since update, "admin/firesale/products/edit/5"

A Database Error Occurred

Error Number: 1366

Incorrect integer value: '' for column 'firesale_categories_id' at row 1

INSERT INTO `default_firesale_products_firesale_categories` (`row_id`, `firesale_products_id`, `firesale_categories_id`) VALUES ('5', '18', '')

Filename: /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/addons/default/modules/firesale/models/products_m.php

Line Number: 304

**Comment by jHoldroyd** [comment]
Should be fixed now
