### ISSUE TITLE
Tax and Shipping calculations are still wrong

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#428]
The total of an order is still less the tax on the shipping.

On the payment page if I add up price_sub_tax + price_sub + price_ship_pre + price_ship_tax it is greater than the price_total (which is what the customer gets charged.) the difference is the shipping tax cost.

**Comment by iknowfoobar** [comment]
I remember this being fixed and I have a firesale site running where it is working properly so I believe that whatever you had fixed has recently been broken again.

**Comment by iknowfoobar** [comment]
Is anyone able to look at this problem?

**Comment by AJSturrock** [comment]
I'll have a look into this again this afternoon for you

**Comment by iknowfoobar** [comment]
Cheers Adam, as a current workaround I am just reporting shipping prices excluding VAT, but this isn't quite right as the tax figure shown on the order and emails isn't strictly correct as it doesn't include the tax for the shipping (which isn't being added on to the price)

**Comment by AJSturrock** [comment]
I've pushed a fix for this a6173bcbe4d10f84e81bd1dd451e1e849009b9f0 let me know if it resolves the issue!

**Comment by iknowfoobar** [comment]
That appears to be working! I am just running some complete process checks including payment.

**Comment by iknowfoobar** [comment]
Working fine, thanks! Can you merge into pro?

**Comment by AJSturrock** [comment]
I'll get Chris to merge any updates that he might have missed asap.
