### ISSUE TITLE
Hardcoded JS and CSS

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#429]
Please can the hard coded firesale.js and firesale.css be removed and added via the theme not by the controllers. I am constantly having to comment it out as our themes don't require them.

**Comment by AJSturrock** [comment]
I've added a setting for this now to toggle the use of the css and js on the front end. Looks like it's only the cart controller and public controller event now. b77a7b3cc5ebd856410581091d37246be917f1e7 and 339f90bea6af856774783e194eb8a75369a75f51

**Comment by iknowfoobar** [comment]
Cheers, I think they might be added in by the SEO module on Pro as well.

**Comment by AJSturrock** [comment]
The seo css and js should only be added to the admin product and category create/edit pages.

**Comment by iknowfoobar** [comment]
Thanks Adam
