### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#43]
It would be nice to separate permissions: store configuration from administration.

Actually permissions for each FireSALE menu items would be great.

**Comment by chrisnharvey** [comment]
I am currently working on having permissions for each FireSALE menu items as well as permissions for some of the functions of the menu items.

An example would be if you wanted to allow a client could login and edit their payment gateway details, but not install/uninstall or disable a gateway then they could do so.

Same goes for orders. You could allow some users to login and view orders and mark them as dispatched etc, but not edit the order and its contents.

**Comment by chrisnharvey** [comment]
Just added permissions. Only a select few permissions are in there at the moment, let me know what permissions you would like and I'll enable them. Should also be able to set permissions on a per-module basis for FireSALE.
