### ISSUE TITLE
Logged in user saving address on checkout duplication

### ISSUE THREAD

**Issue by alexborton** [firesale/firesale#431]
If a logged in user selects a New address for billing and uses the 'Save address as' field to save the address, if they then select 'Same as billing' for the Shipping address, the address is saved twice and duplicated.

**Comment by AJSturrock** [comment]
Hi Alex, do you have the latest version of FireSale as the shipping address should never save if "same as billing" is selected.

**Comment by AJSturrock** [comment]
Any update on this @alexborton?

**Comment by alexborton** [comment]
Sorry Adam - just returned to the UK. This does seem to have been fixed in the latest version, thanks!
