### ISSUE TITLE
Product pagination not working in admin area

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#432]
I have noticed that the product pagination in the admin area is not working quite right. When you click on a page number that page's products are loaded via the ajax call however page 1 remains selected, this means that the user can never get back to page 1 once they have interacted with the page numbers.

**Comment by AJSturrock** [comment]
Updated the js to correctly switch over to the active page 33a7a239dd310c84d7075cd78b515f24d3d26128
We used to have seperate pages but recently switched over to using ajax only.
