### ISSUE TITLE
Variations being added to Pyro Search Results

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#433]
When show variations is set to false, the variation pages are still being added to the search results meaning that users get 404 pages from search results.

I have fixed this by ensuring that variations are not added to the search results if not required:

In /controllers/admin/products.php

I inserted into line 120:

``` php
// Variations
$show_variations = (bool) $this->settings->get('firesale_show_variations');
```

and changed lines 178-180 to 

``` php
// Add to search
$product = cache('products_m/get_product', $id);

if($show_variations and $product['is_variation'] == '1')
{
    $this->products_m->search($product, true);
}
elseif (!$show_variations and $product['is_variation'] == '0')
{
    $this->products_m->search($product, true);
}
else
{
    $this->products_m->search($product, false);
}
```

**Comment by AJSturrock** [comment]
Thanks for this, added in 18f9506f5c95184f36c059a0fef20b037d369bf0
