### ISSUE TITLE
View More button on Stock Alerts dashboard panel

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#434]
This link leads to a server error page. May just be an incorrect link?

**Comment by AJSturrock** [comment]
Should be fixed in 6e0b19f1e4640cb0d3ec85940f6f7d2913b2f03e we removed the controller for this and it should now use the product filters instead.

**Comment by iknowfoobar** [comment]
Cheers Adam

**Comment by betohorta-mf** [comment]
I have installed firesale on a brand new pyroCMS(2.2) and the Stocks Alerts dashboard aren't work. The links aren't broken. They are just not adding the stock_status parameter on the filters to pass to product_filter ajax controler.

On the products pages, the filters are working fine though. Is this something that you guys can help with?
Thanks in advance
