### ISSUE TITLE
Draft products are publicly accessible and purchasable.

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#439]
If a product is set to draft it's page is still available at the front end. It is also possible to still add the product to a basket and purchase that product.

I would assume that if a product is set to draft it should not be viewable and certainly not able to be purchased?

**Comment by AJSturrock** [comment]
Fixed in 7a1eed62eec11e51cd03644aa76c5e9ffc4f7559

**Comment by iknowfoobar** [comment]
Thanks!
