### ISSUE TITLE
Can i start with an italian translation?

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#44]
What do you think? Cai i start or is better wait some time?

**Comment by jHoldroyd** [comment]
That would be great if you could, I don't see too much changing in the language files before 1.0, just note that anything prefixed in the language file with "[PH]" is a placeholder - I'll try and get those cleaned up before the end of the weekend for you.

**Comment by ChristianGiupponi** [comment]
Ok, no problem for the placeholder, i Will start as soon as i can! 

-- Inviato dal mio Galaxy Nexus

jHoldroyd reply@reply.github.com ha scritto:
