### ISSUE TITLE
product widget

### ISSUE THREAD

**Issue by aaps** [firesale/firesale#442]
It seems that the product widget is not displaying products.
I have tried several things to make it display.

It could be im doing something wrong.

Perhaps something you might want to look at.

**Comment by BhimAle** [comment]
for me its working fine.... do you have images in your product ?

**Comment by aaps** [comment]
i filled in all the fields, so an image too.
Could that have broke it ?

**Comment by BhimAle** [comment]
i think not. there might be some other problem that is preventing your
image to be shown. Have you check your image in the files ? Is your image
present in your files ?

**Comment by aaps** [comment]
well it is not only the image but also the text, there is nothing showing but 'No products found'
products are Uncategorised and in the default tax band.
Perhaps that could have something to do with it.
Also i have checked the image tab and i can upload an image in that without errors.

**Comment by aaps** [comment]
Ok i fixed this, it guess it was a widget area name.
