### ISSUE TITLE
Blank pages after install

### ISSUE THREAD

**Issue by MarcPinnell** [firesale/firesale#451]
Installed FireSale today. Created categories, added a product, etc. Went to the public side of things and hit domain/categories/category-slug and got a completely blank page. No error, nothing.

Docs mention something about FireSale adding pages, but I don't see anything in the admin >> pages that was added. Just my pages.

**Comment by MarcPinnell** [comment]
Additional info on this. 

http://domain.com/category/category-slug pulls a 404, but doesn't use the 404.html file, just returns a blank, white page.
http://domain.com/category/pulls the default.html layout file with the main content area blank.

If I change the default.html file's main area from {{ page:body }} to {{ template:body }} then:

http://domain.com/category/category-slug pulls a 404, but doesn't use the 404.html file, just returns a blank, white page.
http://domain.com/category/pulls the default.html layout file with the word "category" in the main content area.

It's as if it isn't seeing the firesale module view pages or something. I have checked and I have 777'd the entire site folder (just to be sure). Is there a special layout file that I am missing?

**Comment by jHoldroyd** [comment]
I'd suggest checking routes have been added, it looks like they're not being found. You can re-build the routes in firesale/routes and add them to the file again. Also, we don't add pages to your pages that would be insane, instead we generate them based on the routes you want to use.

**Comment by MarcPinnell** [comment]
I checked the routes. They are in the admin, the DB and the config file... I will work on getting on a live server and will email you then so you can take a look.

Marc Pinnell

**Comment by zvineyard** [comment]
@MarcPinnell Were you able to solve this?

**Comment by MarcPinnell** [comment]
I don't think so. I finally gave up and took the store offline. Whole project/site ended up getting shelved.

Marc Pinnell

**Comment by zvineyard** [comment]
Sorry to hear that @MarcPinnell. Please let me know if you hit this problem again. I'm picking up the FireSale project behind the original developers (who've quite working on it). I'd be happy to help.
