### ISSUE TITLE
Saving category keywords (error 500)

### ISSUE THREAD

**Issue by yveveke** [firesale/firesale#452]
When you add keywords to a category (and I think also with products) I get an internal server error through an ajax call to admin/firesale/categories/9

The error is the following

``` php
<h1>A Database Error Occurred</h1>
<p>Error Number: 1406</p><p>Data too long for column 'keyword_hash' at 
row 1</p><p>INSERT INTO `default_search_index` (`keywords`, 
`keyword_hash`, `cp_edit_uri`, `cp_delete_uri`, `title`, `description`, 
`module`, `entry_key`, `entry_plural`, `entry_id`, `uri`) VALUES ('', 
'duikautomaat,eerste trap,tweede trap,duikuitrusting', 
'admin/firesale/categories#9', 'admin/firesale/categories/delete/9', 
'Ademautomaten', 'De duikautomaat is een cruciaal onderdeel van je 
duikuitrusting.&nbsp; Betrouwbaarheid, degelijkheid en performantie zijn de 
belangrijkste eigenschappen.', 'firesale', 'firesale:category', 
'firesale:categories', '9', 'category/ademautomaten')</p>
```

It seems the call put the keywords as keywords_hash, and doesn't generate the hash

edit : I have FireSale Pro v1.0

**Comment by zvineyard** [comment]
@yveveke Were you able to solve this problem?

**Comment by hsq** [comment]
Have a check there... How long is the db field? probably too short. 
keyword_hash varchar 255

**Comment by zvineyard** [comment]
I've pinpointed where this bug is at. I'll add the fix and get back you about a solution.

**Comment by zvineyard** [comment]
Essentially, when you add a category, it gets indexed in PyroCMS's search module. The keyword list you are providing is too long for the default PyroCMS limit inside the search module. You can probably just adjust that DB column to accept a longer string.
