### ISSUE TITLE
Beginner for Firesale module in Pyrocms 

### ISSUE THREAD

**Issue by palashjain** [firesale/firesale#458]
HI,
there i got some issues, related to firesale in pyrocms.
I installed firesale perfectly in Pyrocms, but now don't know how to integrate pages from firesale to pyrocms or admin dashboard.

please mail me - sparkleacessories@hotmail.com

Thank you.

**Comment by BhimAle** [comment]
what are your issues ? can you be little more specific ?

**Comment by palashjain** [comment]
Actually i made catgories in firesale bt it doesn't show in pyrocms or on website
why this happen i don't know

**Comment by BhimAle** [comment]
If you have install the firesale perfectly then you will see many firesale widgets. Initialize the new widgets of firesale for example: Firesale Products{{ widgets:area slug="products" }}. 
Then after you do that press on view code you will get something like this : {{ widgets:instance id="2"}}  . Now copy these code and paste to the content of the pages you want to show the products.

**Comment by zvineyard** [comment]
@palashjain Were you able to get your problems resolved?
