### ISSUE TITLE
Can't add products on 1.2.1 or 1.2.2

### ISSUE THREAD

**Issue by renich** [firesale/firesale#459]
Hello,

I can't add products. Using NginX with normal rewrite rules.

Here's a screenshot
![screenshot from 2014-06-21 00 47 27](https://cloud.githubusercontent.com/assets/225115/3347963/932e60ca-f907-11e3-9288-001e55bdea72.png)

**Comment by zvineyard** [comment]
It looks like you might be missing the Multiple Relationship Field Type. Try installing it and see if your problems are solved. https://github.com/adamfairholm/PyroStreams-Multiple-Relationships

**Comment by zvineyard** [comment]
Hi @renich, did adding the Multiple Relationship Field Type solve your problem?

**Comment by renich** [comment]
Actually, I abandoned the project. Sorry.

**Comment by zvineyard** [comment]
No problem. I hope you check out this project for a future project. I'm pretty confident adding the Multiple Relationship Field Type would have solved this problem for you.

**Comment by renich** [comment]
Will do. Many thanks
