### ISSUE TITLE
404 loading multiple.js/css 

### ISSUE THREAD

**Issue by codeplexnl** [firesale/firesale#466]
After a fresh install of pyrocms and firesale, everything is working except adding a new product.
I cannot select a category. In the javascipt console i get a 404 error on the following files:

streams_core/field_asset/js/multiple/multiple_drag.js
streams_core/field_asset/css/multiple/multiple.css 

How can i fix this?

**Comment by codeplexnl** [comment]
The solution for my problem was to change my nginx config.

**Comment by seventhqueen** [comment]
Do you have a hint for that nginx change? Thanks @codeplexnl
