### ISSUE TITLE
Manual order issue

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#47]
when i try do add an order i have this SQL error:

Errore del database

Error Number: 1364

Field 'shipping' doesn't have a default value

INSERT INTO `default_firesale_orders` (`status`, `created`, `created_by`, `ordering_count`) VALUES ('1', '2012-08-04 22:43:53', '1', 1)

Filename: /Applications/MAMP/htdocs/PyroCMS_PRO/modules/streams_core/models/row_m.php

Line Number: 1300

**Comment by jHoldroyd** [comment]
Should be taken care of now
