### ISSUE TITLE
Missing key in Language file

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#48]
No all the field are in the language file, for example some strings of dashbord are written in the view and not in the language file

**Comment by jHoldroyd** [comment]
I'm going through at the moment trying to clean up any of these issues, a number of our still in-development areas are like this but I'll make sure this is rectified asap.

**Comment by jHoldroyd** [comment]
That should be everything done for the admin side, there are however a number of JS entries that still need taken care of which I'll be sorting a little later

**Comment by chrisnharvey** [comment]
I've made several additions to the language file as of commit 017db5b and 7037f90

**Comment by ChristianGiupponi** [comment]
I will look as soon as possibile to translate it!

**Comment by chrisnharvey** [comment]
Not sure if this one can be closed yet?

**Comment by ChristianGiupponi** [comment]
I think you can close for now, I do not find other string to translate but I don't have look at everything!

**Comment by chrisnharvey** [comment]
No problem, thanks for all your help.

**Comment by jHoldroyd** [comment]
There may be a few leftovers in the js files (but they're just duplicates from the actual UI), having said that the vast majority will be done
