### ISSUE TITLE
Suggestion: Have a unique menu item name

### ISSUE THREAD

**Issue by rgogulakrishnan** [firesale/firesale#5]
How about having a menu item as "Third Party" like that so that all the thirdparty addons bought from store can be grouped under this menu item. 

This is has to be decided along with PyroCMS team as this will prevent keep on adding new menu items and makes header wider!

Let me know your thoughts!

**Comment by rgogulakrishnan** [comment]
[Issue #1605](https://github.com/pyrocms/pyrocms/issues/1605) has been raised as a follow-up. 

Lets see!!

**Comment by jHoldroyd** [comment]
I see why you'd want to do that, but I really don't expect you to get that far with it. There are many reasons to not do it, mainly you want to reduce how many clicks it takes a user to get to a certain item, and adding another dropdown for addons will just get messy.

**Comment by rgogulakrishnan** [comment]
This has nothing to do with FireSALE. There will be menu [re-structure](https://github.com/pyrocms/pyrocms/issues/1605#issuecomment-7082217) in PyroCMS v2.2 and you cannot have a module name as main menu item. 

And its out of scope as of now!
