### ISSUE TITLE
Product slug

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#50]
Product slug does not strip anything, it only mirrors the title field.

In addition PyroCMS blog module has full implementation for Unicode characters, I suggest to follow that.

I am using Lithuanian language, additional char conversion must be e.g. š -> s, ę -> e ...

**Comment by jHoldroyd** [comment]
I think this is more of an issue to do with Streams since we use their slug field_type, however I will look into a fix for this and get back to you soon.
