### ISSUE TITLE
Missing Field 'children'

### ISSUE THREAD

**Issue by james182** [firesale/firesale#55]
Got the latest version of firesale

A Database Error Occurred

Error Number: 1054

Unknown column 'children' in 'order clause'

SELECT `id`, `title`, `slug` FROM (`default_firesale_categories`) WHERE `status` = '1' AND `parent` = 0 OR `status` = '1' AND `parent` IS NULL ORDER BY `children` desc LIMIT 6

Filename: /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/addons/default/modules/firesale/plugin.php

Line Number: 59

**Comment by jHoldroyd** [comment]
That's just the theme being outdated and not up to date with the latest changes. It's not a core problem so I'm closing the issue, however I will try and get the theme updated on DB for you a little later.

Thanks for the reminder though
