### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by james182** [firesale/firesale#6]
i have just grabbed the latest version and installed, but the database tables are not installed:
- Products
- Gateways
- Orders
- Shipping

And settings goes to settings but with no FireSALE tab.

**Comment by jHoldroyd** [comment]
Any error messages shown during install?
Also could you check that after uninstall all tables were dropped correctly before trying again

**Comment by james182** [comment]
i manually deleted the tables and everything and then re-installed but the above tables didn't get installed

**Comment by jHoldroyd** [comment]
Almost all of our tables are streams powered and if you just dumped the tables many of the extra information streams stores is still present and presumably caused your install issues.

You're going to have to manually drop all of the data relating to the module from the streams tables before trying again.
