### ISSUE TITLE
Upgrade to the latest version of ci-merchant

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#61]
Our version of ci-merchant is a bit out of date now. Updating to the latest version is something that I'm working on, but as ci-merchant now uses language files for gateway names, field names etc then this isn't going to be an easy migration because I wrote the gateways library/interface so gateways can be "plug and play" and it pulls out the required settings automatically.

It wouldn't be the fantastic "modular" gateway system as it is today if you need to add a language key for each gateway title, setting and parameter.

I am currently working on a solution which will allow the modules to be "plug and play", available in multiple languages, and of course, up-to-date with the latest version of ci-merchant.

**Comment by jHoldroyd** [comment]
This should be completed now and there's only one or two small issues left as far as I'm aware and that's just with the views. I'll wait for Chris to make the final push but this is more or less ready for release.

**Comment by chrisnharvey** [comment]
This is all pretty much done, just need to add the new gateway views and populate the language file with information about the new gateways... Oh the joys.

**Comment by chrisnharvey** [comment]
Mission complete!
