### ISSUE TITLE
Doesn't update cart

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#67]
While trying to update quantity of item in cart, there nothing happens.

**Comment by chrisnharvey** [comment]
The default module views are not quite finished. I'm assuming this is the problem but I will look into this and get back to you with updates.

**Comment by from2day** [comment]
Not the views:

```
// No checkout without items
if ( ! $this->fs_cart->total_items())
```

Some times price can be zero, so we need to check item count.

**Comment by chrisnharvey** [comment]
I thought I'd updated that method a while ago. Obviously not. I wasn't aware that your price was set to zero.

Thanks for the update.
