### ISSUE TITLE
Doesn't add item to cart with unicode chars in title

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#68]
Doesn't work: ąčęėįšųūž.

**Comment by chrisnharvey** [comment]
Apologies for the issue you're having. I'll look into this ASAP.

**Comment by jHoldroyd** [comment]
Since Chris doesn't seem to have had a chance to look into this yet for you could you please let me know the url that you are using to insert the product to the cart? Either inspect the element of the button/link it's using or trace it with a browser plugin. It should be something like /cart/insert/ID/COUNT

Given that we use the ID to insert a product the name of it shouldn't matter, I just wanted to amke sure that the URL structure is correct before looking into the cart code.

Thanks for the report though

**Comment by from2day** [comment]
"/cart/insert/91/1" 
URL seems correct always. (in style: cart/insert/ID/COUNT )

I have checked many problematic links, all of them was with unicode chars. I just didn't get time to debug deeper for ajax response.

**Comment by chrisnharvey** [comment]
Looking into this now. Apologies for the delay.

**Comment by chrisnharvey** [comment]
Just done some debugging and it seems that this might be an issue with streams. I could be wrong but the data that comes out of streams when we retrieve the product is malformed.

For example:
ąčęėįšųūž came out as Ä…ÄÄ™Ä—Ä¯Å¡Å³Å«Å¾

I will keep looking into this though and keep you updated.

**Comment by from2day** [comment]
It's not streams problem.

http://codeigniter.com/forums/viewthread/186579

In front_cart.php on 27 I've set:

```
        $this->fs_cart->product_name_safe = FALSE;
```

The right way would be to overwrite validation rules of CI cart. Maybe to set it in config files?

**Comment by chrisnharvey** [comment]
Many thanks for the info. I will implement this ASAP (hopefully today)

**Comment by chrisnharvey** [comment]
I think I'll update the RegEx so it respects unicode characters.

**Comment by jHoldroyd** [comment]
If you can get this implemented today that'd be great, it's also causing me a few issues testing other modules before handing out access to people!

**Comment by chrisnharvey** [comment]
Will do, what issues is it causing?

**Comment by jHoldroyd** [comment]
I was working with a few updates to more products while away and this issue was flaring up with the expected products and stopped me testing/updating those. Nothing too important really, but it'd be nice to have it fixed so we can test the whole process with special products.
