### ISSUE TITLE
Bug: Can't create category

### ISSUE THREAD

**Issue by james182** [firesale/firesale#7]
When trying to create a category i get this error:

A Database Error Occurred

Error Number: 1054

Unknown column 'title' in 'where clause'

SELECT `id` FROM (`default_firesale_categories`) WHERE `title` = 'T-shirts'

Filename: /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.2/libraries/MY_Form_validation.php

Line Number: 448

**Comment by jHoldroyd** [comment]
Please go check the default_firesale_categories table and make sure all fields are present, title should definitely be there. Were you trying that before you got your install sorted?
