### ISSUE TITLE
Can't update product: "required category field" failed

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#70]
I am using the latest FireSale. 
I have many categories. For each product only one is selected. While updating product gives error.

**Comment by from2day** [comment]
< input type="hidden" name="category" id="category" value="category_16,category_13" >

Is set in "admin/firesale/products/edit/23"

**Comment by from2day** [comment]
When no category is in "selected options" gives error:

Error Number: 1366

Incorrect integer value: '' for column 'firesale_categories_id' at row 1

INSERT INTO `default_firesale_products_firesale_categories` (`row_id`, `firesale_products_id`, `firesale_categories_id`) VALUES ('23', '28', '')

Filename: path_to\system\codeigniter\database\DB_driver.php

Line Number: 344

**Comment by jHoldroyd** [comment]
Are the IDs in the input the correct ones for what you expect? We've seen a number of issues with multiple with these type of results and while we try and patch around them they are deep-routed problems with the multiple field-type which will be replaced when PyroCMS 2.2 is released.

But again I will try and figure something out until that happens.

**Comment by jHoldroyd** [comment]
I've just pushed a commit that will stop it trying to save a blank category and should be better at spliting the correct IDs from the strings - still not fixed the underlying issue with it though as I'm having trouble replicating your issue on this system

**Comment by from2day** [comment]
Are these ID mentioned in comment above? 

```
    <ul id="category_list_2" class="multiple_list category_ml ui-droppable" dds="13">
        <li id="category_22" dds="14" style="cursor: pointer; " class="ui-draggable">< span>Category title 1</span></li>                    
        <li id="category_6" dds="15" style="cursor: pointer; " class="ui-draggable"><span>Category title 2  </span></li>        
    </ul>
```

<...>

```
<input type="hidden" name="category" id="category" value="category_22,category_6">
```

**Comment by jHoldroyd** [comment]
So those are the categories you wish to save and I presume that this still isn't happening for this particular product even after the latest commits? Because the data there looks correct for what we expect to be posted

**Comment by from2day** [comment]
Yes, the categories are with correct id's. It seems as if category field is not set somewhere.
I have tried on new installation with the same data. Error remains.

Is there any way of debugging it i could try?

**Comment by jHoldroyd** [comment]
Inside the products model file on line 324 there is a function called update_categories, firstly check the third variable it is being passed ($categories) and make sure that is the same as the input field you posted above. After that check that it is being split correctly into the array (line 331) and from there you should be able to tell what's happening. You could also go a little further and check that the SQL query being executed is correct by adding a line after 351 with:

echo $this->db->last_query();

Let us know how you get on and we'll try and help as much as we can.

**Comment by from2day** [comment]
url "admin/firesale/products/edit/4"
debug:

```
line 324: string(34) "category_17,category_16,category_5" 
line 331: array(3) { [0]=> string(11) "category_17" [1]=> string(11) "category_16" [2]=> string(10) "category_5" } 
line 351: INSERT INTO `default_firesale_products_firesale_categories` (`row_id`, `firesale_products_id`, `firesale_categories_id`) VALUES ('4', '28', '17')
INSERT INTO `default_firesale_products_firesale_categories` (`row_id`, `firesale_products_id`, `firesale_categories_id`) VALUES ('4', '28', '16')
INSERT INTO `default_firesale_products_firesale_categories` (`row_id`, `firesale_products_id`, `firesale_categories_id`) VALUES ('4', '28', '5')
```

Lastly, categories are saved, however error keeps popping up, that category field is required.

**Comment by jHoldroyd** [comment]
Looks like it's either an issue with the multiple field-type or it's with our handling of the validation it provides, I'll look into either bypassing it or making categories not required until 2.2 is released in a few weeks. I think I've mentioned it before but we'll be doing a number of updates to the core to integrate with the new grid field type and drop support for the outdate multiple stuff we added as a temporary measure.

Thanks for the continued reports though and I'll try and get something up for you tomorrow if I can.

**Comment by chrisnharvey** [comment]
Are you still experiencing this issue @pafbone?

**Comment by from2day** [comment]
Yes.
Categories are saved, but other fields are not updated.

**Comment by from2day** [comment]
How are things going on with this isue?

**Comment by jHoldroyd** [comment]
This should be taken care of, I switched back to using the multiple methods of updating but had to implement a few fixes to the data first and a new temporary function has been added until 2.2

I'll leave this open until you confirm things are working on your end, everything is great here so hopefully we can close this one!

**Comment by from2day** [comment]
Yes, everything works. Thanks.
