### ISSUE TITLE
Multiple currencies

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#73]
The ability to utilise a number of different currencies for products, which will be automatically generated based on the default price and converted using a cached version of the open exchange rates api (written as a basic library so if you want to use another service you can do so).

You will also be able to select which currencies you'd like to enable and to lock/update the prices manually, with an optional multiplier - for instance increasing the conversion rate from GBP to USD by 5% to cover any extra costs etc.

We chose the open exchange rates api due to positive past experiences and because we're caching it in the database a free account is way more than enough to cover the 1,000 requests/month it provides.

You can read more about the service here: http://openexchangerates.org/documentation

**Comment by jHoldroyd** [comment]
Well apart from some small testing left to do this is all but complete, closing now as there are little to no issues remaining and they can be handled as additional issues.
