### ISSUE TITLE
Prevent from quick edit categories

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#74]
When multiple categories are assigned to product, making quick edit, saves only one category.

**Comment by jHoldroyd** [comment]
That's something I'm working on at the moment, the javascript isn't populating the dropdowns correctly but I hope to have that solved some time today.

**Comment by jHoldroyd** [comment]
That should be that taken care of, if you want to remove a category via quick edit, just change the option to "select a category" and due to the change I made earlier, since it can't find a valid category, it will be removed from that product.
