### ISSUE TITLE
Convert navigation to backend dropdown

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#78]
The amount of items that can be added to the secondary navigation for modules is limited, so we need to change the navigation to Pyro's dropdown in the backend.

This will also allow FireSALE modules to have sub-menu's which would be great for things like discount codes so we could see the "Active" and "Expired" codes.

I probably should've thought of a better example than that ;)

**Comment by jHoldroyd** [comment]
The only issue I have with that is it requires more actions to navigate through the system and we then have to split the modules up to achieve the extra menu items. I do fully agree the number of items we can add may be a little too much and we need a solution, I'm just not sure this will be the best one.

**Comment by jHoldroyd** [comment]
This got done with 1.2
