### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by james182** [firesale/firesale#8]
How does the frontend store work?

New nav link with FireSALE Module selected gives nothing  on click

http://localhost/users/orders

also the navigation for categories:

A PHP Error was encountered

Severity: Notice

Message: Use of undefined constant children - assumed 'children'

Filename: Lex/Parser.php(725) : eval()'d code

Line Number: 77

**Comment by james182** [comment]
Any thing on this?

**Comment by jHoldroyd** [comment]
We're looking into it, it's not something we'd ever seen until using it on a different server and it only happened twice. So we are trying to find a fix but are having huge problems replicating it to debug

**Comment by james182** [comment]
i just install theme and that's all, do i have to do anything else?

**Comment by jHoldroyd** [comment]
Not really, as long as you have routes enabled ticked in your settings, everything should work. You can stop the errors by removing the lex tag on line 77 and it's closing tag and it will stop the children error...but we currently have no clue why it's happening.

**Comment by jHoldroyd** [comment]
After testing we've found that this isn't an issue with this area of the module, it's an issue with the theme - which at this time we're not supporting (at least not here) and the above advice is a workaround that will remove the error.

So I'm closing this for now, but if you still need any more help with it DM me on Twitter.
