### ISSUE TITLE
Sub-modules do not show in permissions

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#81]
FireSALE sub-modules do not show up when assigning permissions to a group.

**Comment by ChristianGiupponi** [comment]
Are you talking about "FireSALE Search (Basic)" and "FireSALE Shipping"?

**Comment by chrisnharvey** [comment]
Yeah, can you see those? It might just be that the version I'm running for a client project is a bit out of date.

**Comment by ChristianGiupponi** [comment]
No I can't but I think that the reasion is because the other two modules doesn't have the roles filed in the dateils.php

**Comment by chrisnharvey** [comment]
True, but I believe that all modules should show up there regardless (just to give the user access to the entire module).

**Comment by ChristianGiupponi** [comment]
You're right, that's strange...

**Comment by chrisnharvey** [comment]
I think I know whats going on here. I'll push a fix tonight.

**Comment by chrisnharvey** [comment]
Seems like this one won't fix without editing Pyro's core. The permissions page checks that "is_backend" is set to true, which is is not for our sub-modules, thats what keeps them out of the dropdown menu.

We plan to move our menu to the dropdown in a future minor release, so this one will have to wait until then.

**Comment by jHoldroyd** [comment]
Fixed...finally.
