### ISSUE TITLE
Add the ability to autoload models, libraries etc.

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#83]
Whilst developing modules for FireSALE I noticed that we need to edit the core to load models, libraries and helpers into core views (like the cart view)

So if I had a discount code model and need to access it in the cart view which I overloaded using the theme then I'm either going to have to edit the core of FireSALE or load the model inside the view (which is never a good idea)

I'm working on an autoload system at the moment.

**Comment by jHoldroyd** [comment]
Referenced the wrong issue sorry -.-

**Comment by jHoldroyd** [comment]
Do we still need this given the changes coming in Pyro 2.3?

**Comment by chrisnharvey** [comment]
Not really. When we move to laravel, autoloading will be done automatically. Closing.
