### ISSUE TITLE
Can't install FireSALE

### ISSUE THREAD

**Issue by james182** [firesale/firesale#84]
Fatal error: Cannot use object of type stdClass as array in /Applications/MAMP/htdocs/PyroCMS-Professional-v2.1.3/system/cms/modules/streams_core/models/streams_m.php on line 449

this is a clean install of 2.1.3 and firesale

**Comment by ChristianGiupponi** [comment]
Try to upgrade pyrocms to 2.1.4

**Comment by jHoldroyd** [comment]
That was a known issue with 2.1.3 that we discovered a while back and a fix was published in 2.1.4 and as such FireSale cannot be installed correctly on 2.1.2 and 2.1.3 (iirc). As Christian said you will need to update your version of pyro before continuing.
