### ISSUE TITLE
Enhancement: Disable Installation if incompatible PyroCMS

### ISSUE THREAD

**Issue by chadwithuhc** [firesale/firesale#86]
Hey Guys,

I would recommend doing a check on the install if the user has PyroCMS 2.1.4 or higher just so they don't try to install it and get errors. I did this on accident first, then later on realized I wasn't running 2.1.4 yet. It'd be nice to show a simple error message.

**Comment by chrisnharvey** [comment]
This is something that I've had planned to add, as well as checking for the Multiple Field Type and a couple of other checks.

Thanks for suggesting.
