### ISSUE TITLE
Error on save of "FireSALE Dummy" gateway

### ISSUE THREAD

**Issue by jellis** [firesale/firesale#87]
Although I realise this is not intended to be edited, when hitting "Save" after entering the editing area, the user is presented with a list of errors stemming from an empty array.

**Comment by chrisnharvey** [comment]
I'll have to look into this one as I couldn't reproduce it. What errors were showing? Is this when editing a gateway in the admin area?

**Comment by jellis** [comment]
Yup, just when I clicked on "Edit" for the Dummy gateway and then saved it (hadn't changed anything).

**Comment by jHoldroyd** [comment]
Could you please post the line numbers the errors are being sent from please?

**Comment by jHoldroyd** [comment]
Was just able to reproduce this and found it was tied to an undefined array for that gateway, taken care of now.
