### ISSUE TITLE
Images not uploading

### ISSUE THREAD

**Issue by jellis** [firesale/firesale#88]
Using PyroCMS 2.1.4 Community on OSX Mountain Lion with MAMP (PHP 5.3) and FF15.

Dragging and dropping images into products appears to work.  A tick appears over the image and the upload progress bar gets filled to 100%, however, the image is never uploaded to the file system and stored against the product.

**Comment by jellis** [comment]
This is intermittently reproducible. Initially, I was hitting "Save".  However, having hit "Save and Exit" actually got the image stored.

**Comment by chrisnharvey** [comment]
@jHoldroyd will have to look into this one as it is his area.

**Comment by parafas** [comment]
I got some issues using another module (pyrocms) and FF15.
there is some kind of caching that is keeping the form with the old
information, not allowing to update with the new one.
but the database has been updated.

**Comment by jHoldroyd** [comment]
Can I just ask, have you saved the product before uploading images for it? It shouldn't give you access to the image upload section on product creation until then but something may have gone wrong with that and I just wanted to make sure this wasn't the case before looking further into the upload issues.

If it isn't the case and you think the images should have uploaded, could you please check the database as suggested above to see if the images were stored correctly.

**Comment by jHoldroyd** [comment]
Not able to reproduce this issue myself so if you're able to answer the above questions, and things are going into the database then I'm inclined to agree with @parafas that this is a browser caching issue. To be sure though I'd also ensure that your upload folder permissions are set correctly.

**Comment by ChristianGiupponi** [comment]
Same problem, I will try to delete the cache later today and I will tell you as soon as possible!

**Comment by jHoldroyd** [comment]
Can I just ask quickly too, what image format are you using and what is the image name?

**Comment by parafas** [comment]
My workaround was including a timestamp in the redirection url after
editing a register.

**Comment by jHoldroyd** [comment]
I'll add something like that into the core in a moment, but we have just found an issue with certain image formats that I'm currently trying to take care of now - namely gif and bmps. Not terribly common formats for the web, but certainly something that we feel needs fixed.

**Comment by jellis** [comment]
Just confirming that I was uploading jpegs, and the folder permissions were set correctly.  Apologies for the late reply.

Issue has now been rectified?

**Comment by jHoldroyd** [comment]
The issue should be fixed yes and if it still doesn't work it should correctly report as to why.
