### ISSUE TITLE
Error on completion of payment with Firesale Dummy gateway

### ISSUE THREAD

**Issue by jellis** [firesale/firesale#89]
PyroCMS 2.1.4 Community

Using Firesale Dummy gateway and paying with the test credit card produced an error.

"An Error Was Encountered

Unable to locate the model you have specified: search_m"

Reproducible infinite amount of times.

**Comment by chrisnharvey** [comment]
I did get an error, but not this one. Have you installed the firesale_search and firesale_shipping modules?

**Comment by jellis** [comment]
Yes, both of these modules are installed.

**Comment by jHoldroyd** [comment]
It was a typo in the search details file that was used for tracking sales after a search was performed, this should be taken care of as well as fixing the other issue mentioned with the email key missing.
