### ISSUE TITLE
Have settings within the addon

### ISSUE THREAD

**Issue by rgogulakrishnan** [firesale/firesale#9]
I remember once, while talking with phil, that the module specific settings should be moved to respective modules unless it has some global settings.

As the firesale module settings has nothing to do with global settings. These settings ars specific to this module only.

**Comment by jHoldroyd** [comment]
It is something we've already planned to do and it's just a matter of time. We want to combine all of settings, including gateways into a tabbed settings page that third-party firesale modules can also attach into to keep everything in one, easy to use location.

It's just not a major priority, but it is planned and as soon as we get time it'll be done!

**Comment by rgogulakrishnan** [comment]
Cool!

**Comment by jHoldroyd** [comment]
After a few discussions I don't think this is any longer a priority and isn't something we're going to be doing anymore. The system is there to add settings and is intended to be customised by additional modules, recreating the wheel to perform the same purpose seems fruitless and a waste of time to be honest. It would have been nice to consolidate everything but we're integrating into a system and plan to use as many elements of that as we can.
