### ISSUE TITLE
Category list issue

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#90]
I have just created a new category named "Costums" with no product in it.
If I insert manualy the link "category/cosums" in the browser as the docs says the page is show correctly...but if I click on "List" instead "Grid" I receive this error:

{"status":false,"message":"Found no files matching system\/cms\/modules\/pages\/css\/firesale.css","data":""}

and the url change in /category/style/list

Same thing appen if I click on the order option in the select.

Just to be more clear: http://www.diigo.com/item/image/32ya3/q3vt

**Comment by jHoldroyd** [comment]
I'll look into this one for you, more than likely it's just a routes issue or something similar, these were quick little things we added for a client site that we felt were kinda cool features and I'm not sure have been maintained fully throughout the dev process.

**Comment by jHoldroyd** [comment]
The route was indeed missing, I did a few other checks and everything seems to be working with it too...which was a nice surprise!
