### ISSUE TITLE
Cart - do not respect the quantity

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#93]
In the single product page if iI select 10 in the quantity field and then I go to the cart I can see just 1 product.
If I get back to the product page and I select 10 again the cart update the quantity by 1 again.

**Comment by jHoldroyd** [comment]
The cart does respect the quantity you select, however if the stock isn't there to cover it, we automatically fall-back to the maximum available. So if you add 10 to the cart and 3 are in stock, the cart will show 3. Having said that we could make it a little easier on the user by showing them a message stating that the quantity is not available with a flash message.

**Comment by ChristianGiupponi** [comment]
Agree for the flash message.
But I have set 100 in stock and if I try to add 10 to the cart it shows me only 1.

**Comment by jHoldroyd** [comment]
Ah that would appear to be an issue with the views, I'll look into that now.

**Comment by jHoldroyd** [comment]
This should be taken care of now
