### ISSUE TITLE
Speed improvements - add caching

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#94]
When we have lots of products and categories etc, the frontend is noticeably slow. I need to add caching to help speed things up.

**Comment by chrisnharvey** [comment]
@jHoldroyd has added run-time caches to several sections of the core. Will enhance with some extra caching soon.

**Comment by jHoldroyd** [comment]
I think that's all of the caching that'll be going into 1.1, if needed we can add more in minor or the next major version, closing.
