### ISSUE TITLE
Product 404 page

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#99]
When attempting to view a product that does not exist (i.e. /product/i-dont-exist), I get a JSON string with the following data:

`{"status":false,"message":"Found no files matching system\/cms\/modules\/pages\/css\/firesale.css","data":""}`

**Comment by jHoldroyd** [comment]
Sorted.

**Comment by jellis** [comment]
I've just pulled and updated my codebase, but experience a similar issue when clicking on "List" in the category view.  It also happens when ordering via the drop-down in the category view.

**Comment by jHoldroyd** [comment]
The fix for that is in the readme, you must install an extra route that was originally missed which will activate the link you're using now.
